"""``GENERATED … AS IDENTITY`` columns and ``ALTER SEQUENCE``.

An identity column is an integer column backed by an owned sequence (like SERIAL).
``GENERATED ALWAYS`` rejects a user-supplied value (accepting ``DEFAULT``);
``GENERATED BY DEFAULT`` behaves like SERIAL. ``ALTER SEQUENCE`` adjusts a
sequence's parameters (RESTART / INCREMENT / MIN / MAX / CYCLE).
"""

from __future__ import annotations

import pytest

from secantus.sql import errors, run_sql
from secantus.sql.session import Session
from secantus.storage import Storage

DB = "testdb"


@pytest.fixture
def session():
    return Session(database=DB, user="secantus")


@pytest.fixture
def storage(tmp_path):
    s = Storage(str(tmp_path))
    try:
        yield s
    finally:
        s.close()


def run(storage, session, sql):
    return run_sql(storage, DB, sql, session=session)[-1]


def sqlstate(storage, session, sql):
    with pytest.raises(errors.SQLError) as ei:
        run(storage, session, sql)
    return ei.value.sqlstate


# -- GENERATED ALWAYS AS IDENTITY ---------------------------------------------- #


def test_always_identity_autoincrements(storage, session):
    run(
        storage, session, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, n text)"
    )
    run(storage, session, "INSERT INTO t (n) VALUES ('a'), ('b')")
    assert run(storage, session, "SELECT id, n FROM t ORDER BY id").rows == [(1, "a"), (2, "b")]


def test_always_identity_rejects_explicit_value(storage, session):
    run(
        storage, session, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, n text)"
    )
    assert sqlstate(storage, session, "INSERT INTO t (id, n) VALUES (99, 'x')") == "428C9"


def test_always_identity_accepts_default_keyword(storage, session):
    run(
        storage, session, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, n text)"
    )
    res = run(storage, session, "INSERT INTO t (id, n) VALUES (DEFAULT, 'a') RETURNING id")
    assert res.rows == [(1,)]


def test_always_identity_is_not_null(storage, session):
    run(
        storage, session, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, n text)"
    )
    # DEFAULT fills it; an explicit NULL still can't be supplied to ALWAYS.
    assert sqlstate(storage, session, "INSERT INTO t (id, n) VALUES (NULL, 'a')") == "428C9"


# -- GENERATED BY DEFAULT AS IDENTITY ------------------------------------------ #


def test_by_default_identity_autoincrements(storage, session):
    run(storage, session, "CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY, n text)")
    run(storage, session, "INSERT INTO t (n) VALUES ('a')")
    run(storage, session, "INSERT INTO t (n) VALUES ('b')")
    assert run(storage, session, "SELECT id FROM t ORDER BY id").rows == [(1,), (2,)]


def test_by_default_identity_allows_explicit_value(storage, session):
    run(storage, session, "CREATE TABLE t (id int GENERATED BY DEFAULT AS IDENTITY, n text)")
    run(storage, session, "INSERT INTO t (id, n) VALUES (100, 'x')")
    run(storage, session, "INSERT INTO t (n) VALUES ('a')")  # sequence still starts at 1
    assert run(storage, session, "SELECT id FROM t ORDER BY id").rows == [(1,), (100,)]


def test_identity_custom_start_and_increment(storage, session):
    run(
        storage,
        session,
        "CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 10 INCREMENT BY 5), n text)",
    )
    run(storage, session, "INSERT INTO t (n) VALUES ('a'), ('b')")
    assert run(storage, session, "SELECT id FROM t ORDER BY id").rows == [(10,), (15,)]


# -- reflection ---------------------------------------------------------------- #


def test_attidentity_reflects(storage, session):
    run(
        storage, session, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, n text)"
    )
    run(storage, session, "CREATE TABLE b (id int GENERATED BY DEFAULT AS IDENTITY, n text)")
    rows = run(
        storage,
        session,
        "SELECT attname, attidentity FROM pg_attribute "
        "WHERE attname = 'id' AND attidentity <> '' ORDER BY attidentity",
    ).rows
    assert ("id", "a") in rows and ("id", "d") in rows


# -- ALTER SEQUENCE ------------------------------------------------------------ #


@pytest.fixture
def seq(storage, session):
    run(storage, session, "CREATE SEQUENCE s START WITH 1 INCREMENT BY 1")
    run(storage, session, "SELECT nextval('s')")  # 1
    run(storage, session, "SELECT nextval('s')")  # 2
    return storage


def test_alter_sequence_restart_with(seq, session):
    run(seq, session, "ALTER SEQUENCE s RESTART WITH 50")
    assert run(seq, session, "SELECT nextval('s')").rows == [(50,)]


def test_alter_sequence_restart_bare(seq, session):
    run(seq, session, "ALTER SEQUENCE s RESTART")
    assert run(seq, session, "SELECT nextval('s')").rows == [(1,)]  # back to start


def test_alter_sequence_increment(seq, session):
    run(seq, session, "ALTER SEQUENCE s INCREMENT BY 10")
    assert run(seq, session, "SELECT nextval('s')").rows == [(12,)]


def test_alter_sequence_maxvalue_and_cycle(seq, session):
    run(seq, session, "ALTER SEQUENCE s MAXVALUE 3 CYCLE")
    assert run(seq, session, "SELECT nextval('s')").rows == [(3,)]
    assert run(seq, session, "SELECT nextval('s')").rows == [(1,)]  # wraps


def test_alter_sequence_missing_errors(storage, session):
    assert sqlstate(storage, session, "ALTER SEQUENCE nope RESTART") == "42P01"


def test_alter_sequence_if_exists(storage, session):
    assert run(storage, session, "ALTER SEQUENCE IF EXISTS nope RESTART").command_tag == (
        "ALTER SEQUENCE"
    )
