# ALTER TABLE ADD UNIQUE / PRIMARY KEY / FOREIGN KEY, ALTER COLUMN TYPE ... USING,
# CHECK ... NOT VALID -- against PostgreSQL 14.
ALTER TABLE at1 ADD CONSTRAINT at1_a_u UNIQUE (a)
ALTER TABLE at1 ADD UNIQUE (b)
INSERT INTO at1 VALUES (4, 9, 'x')
ALTER TABLE at1 ADD PRIMARY KEY (id)
INSERT INTO at1 VALUES (1, 7, 'q')
ALTER TABLE at1 ADD PRIMARY KEY (id)
ALTER TABLE at2 ADD CONSTRAINT at2_fk FOREIGN KEY (x) REFERENCES at1 (id)
DELETE FROM at2 WHERE x = 5
ALTER TABLE at2 ADD CONSTRAINT at2_fk FOREIGN KEY (x) REFERENCES at1 (id)
INSERT INTO at2 VALUES (99)
ALTER TABLE at1 ALTER COLUMN b TYPE int USING length(b)
SELECT id, b FROM at1 ORDER BY id
ALTER TABLE at1 ALTER COLUMN a TYPE text USING a::text || '!'
SELECT a FROM at1 ORDER BY id
SELECT conname, contype, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid IN ('at1'::regclass, 'at2'::regclass) ORDER BY 1
ALTER TABLE at1 ADD CONSTRAINT at1_ck CHECK (id > 0) NOT VALID
ALTER TABLE at1 VALIDATE CONSTRAINT at1_ck
CREATE UNIQUE INDEX at1_b_idx ON at1 (b)
ALTER TABLE at1 DROP CONSTRAINT at1_b_key
INSERT INTO at1 (id, a) VALUES (10, 'z') ON CONFLICT (id) DO NOTHING
INSERT INTO at1 (id, a) VALUES (1, 'z') ON CONFLICT (id) DO UPDATE SET a = 'upd'
SELECT id, a FROM at1 ORDER BY id
UPDATE at1 SET id = 2 WHERE id = 1
SELECT indexrelid::regclass::text, indisprimary, indisunique FROM pg_index WHERE indrelid = 'at1'::regclass ORDER BY 1
DELETE FROM at1 WHERE id = 1
ALTER TABLE atc ADD PRIMARY KEY (a, b)
INSERT INTO atc VALUES (1, 2, 'dup')
SELECT a, b, v FROM atc ORDER BY a, b
UPDATE atc SET b = 3 WHERE b = 2
SELECT a, b, v FROM atc ORDER BY a, b
ALTER TABLE atc ADD PRIMARY KEY (a)
