DROP TABLE IF EXISTS ac2 CASCADE
DROP TABLE IF EXISTS ac CASCADE
DROP TABLE IF EXISTS rc
CREATE TABLE ac (id int)
INSERT INTO ac VALUES (1), (2)
CREATE TABLE ac2 (id int primary key)
INSERT INTO ac2 VALUES (1)
CREATE TABLE rc (a int, b int)
INSERT INTO rc VALUES (1, 2), (1, 3), (2, NULL)
