# --- ADD COLUMN over a table that already has rows
ALTER TABLE a20 ADD COLUMN c1 text
SELECT id, c1 FROM a20 ORDER BY id
ALTER TABLE a20 ADD COLUMN c2 int DEFAULT 7
SELECT id, c2 FROM a20 ORDER BY id
ALTER TABLE a20 ADD COLUMN c3 int NOT NULL DEFAULT 0
SELECT id, c3 FROM a20 ORDER BY id
# NOT NULL with no default over a NON-EMPTY table must fail
ALTER TABLE a20 ADD COLUMN c4 int NOT NULL
# IF NOT EXISTS is a no-op on a column that is there
ALTER TABLE a20 ADD COLUMN IF NOT EXISTS c1 text
ALTER TABLE a20 ADD COLUMN c1 text
# --- the new default applies to later inserts, not to a value given
INSERT INTO a20 (id, n, s) VALUES (4, 40, 'w')
SELECT id, c2, c3 FROM a20 WHERE id = 4
INSERT INTO a20 (id, c2) VALUES (5, 99)
SELECT id, c2 FROM a20 WHERE id = 5
# --- DROP COLUMN, then re-add the same name: the old values must NOT come back
ALTER TABLE a20 DROP COLUMN c2
SELECT id FROM a20 ORDER BY id
ALTER TABLE a20 ADD COLUMN c2 int
SELECT id, c2 FROM a20 ORDER BY id
ALTER TABLE a20 DROP COLUMN nosuch
ALTER TABLE a20 DROP COLUMN IF EXISTS nosuch
# --- SET / DROP DEFAULT
ALTER TABLE a20 ALTER COLUMN c1 SET DEFAULT 'dd'
INSERT INTO a20 (id) VALUES (6)
SELECT id, c1 FROM a20 WHERE id = 6
ALTER TABLE a20 ALTER COLUMN c1 DROP DEFAULT
INSERT INTO a20 (id) VALUES (7)
SELECT id, c1 FROM a20 WHERE id = 7
# --- SET NOT NULL over a column that HAS nulls must fail; over one that does not, succeed
ALTER TABLE a20 ALTER COLUMN n SET NOT NULL
ALTER TABLE a20 ALTER COLUMN s SET NOT NULL
UPDATE a20 SET s = 'z' WHERE s IS NULL
ALTER TABLE a20 ALTER COLUMN s SET NOT NULL
INSERT INTO a20 (id, s) VALUES (8, NULL)
ALTER TABLE a20 ALTER COLUMN s DROP NOT NULL
INSERT INTO a20 (id, s) VALUES (8, NULL)
SELECT count(*) FROM a20
# --- ALTER COLUMN TYPE
ALTER TABLE a20 ALTER COLUMN n TYPE bigint
SELECT id, n FROM a20 WHERE id = 1
ALTER TABLE a20 ALTER COLUMN n TYPE text
SELECT id, n FROM a20 WHERE id = 1
ALTER TABLE a20 ALTER COLUMN s TYPE int
# --- CHECK constraints added after the fact
ALTER TABLE a20 ADD CONSTRAINT ck_pos CHECK (id > 0)
INSERT INTO a20 (id) VALUES (-1)
ALTER TABLE a20 ADD CONSTRAINT ck_bad CHECK (id > 100)
ALTER TABLE a20 ADD CONSTRAINT ck_pos CHECK (id > 0)
ALTER TABLE a20 DROP CONSTRAINT ck_pos
INSERT INTO a20 (id) VALUES (-1)
SELECT count(*) FROM a20 WHERE id = -1
ALTER TABLE a20 DROP CONSTRAINT nosuch
ALTER TABLE a20 DROP CONSTRAINT IF EXISTS nosuch
# --- several actions in ONE statement, applied in order
ALTER TABLE a20 ADD COLUMN m int, ALTER COLUMN m SET DEFAULT 5
INSERT INTO a20 (id) VALUES (20)
SELECT id, m FROM a20 WHERE id = 20
# --- RENAME COLUMN, including the PRIMARY KEY column
ALTER TABLE a20 RENAME COLUMN c1 TO c1b
SELECT id, c1b FROM a20 WHERE id = 6
ALTER TABLE a20 RENAME COLUMN id TO pk
SELECT pk FROM a20 WHERE pk = 1
INSERT INTO a20 (pk) VALUES (21)
SELECT count(*) FROM a20 WHERE pk = 21
ALTER TABLE a20 RENAME COLUMN pk TO id
ALTER TABLE a20 RENAME COLUMN nosuch TO other
ALTER TABLE a20 RENAME COLUMN s TO n
# --- RENAME TABLE
CREATE TABLE b20 (id int PRIMARY KEY)
ALTER TABLE a20 RENAME TO b20
ALTER TABLE a20 RENAME TO a20new
SELECT count(*) FROM a20new
SELECT count(*) FROM a20
INSERT INTO a20new (id) VALUES (30)
SELECT count(*) FROM a20new WHERE id = 30
ALTER TABLE a20new RENAME TO a20
# --- errors on a table that is not there
ALTER TABLE nosuch20 ADD COLUMN x int
ALTER TABLE IF EXISTS nosuch20 ADD COLUMN x int
ALTER TABLE nosuch20 RENAME TO other20
# --- ALTER COLUMN TYPE: the cast rule is about the TYPES, not the values.
# `text -> int` is refused even when every value would convert cleanly.
DROP TABLE IF EXISTS t21
CREATE TABLE t21 (a text, b int, c date, d bool, e json)
INSERT INTO t21 VALUES ('1', 1, '2020-01-01', true, '1')
ALTER TABLE t21 ALTER COLUMN a TYPE int
ALTER TABLE t21 ALTER COLUMN a TYPE date
ALTER TABLE t21 ALTER COLUMN b TYPE text
ALTER TABLE t21 ALTER COLUMN b TYPE bigint
ALTER TABLE t21 ALTER COLUMN b TYPE numeric
ALTER TABLE t21 ALTER COLUMN b TYPE bool
ALTER TABLE t21 ALTER COLUMN d TYPE int
ALTER TABLE t21 ALTER COLUMN c TYPE timestamp
ALTER TABLE t21 ALTER COLUMN c TYPE text
ALTER TABLE t21 ALTER COLUMN e TYPE jsonb
ALTER TABLE t21 ALTER COLUMN a TYPE varchar(3)
SELECT a, b, c, d FROM t21
