RESET ROLE
DROP VIEW IF EXISTS av_v CASCADE
DROP VIEW IF EXISTS av_w CASCADE
DROP VIEW IF EXISTS av_vv CASCADE
DROP TABLE IF EXISTS av_t CASCADE
DROP ROLE IF EXISTS av_bob
CREATE ROLE av_bob
CREATE TABLE av_t (id int, v int DEFAULT 5)
INSERT INTO av_t VALUES (1, 1)
CREATE VIEW av_v AS SELECT id, v FROM av_t
CREATE VIEW av_vv AS SELECT id, v FROM av_v WHERE id > 0
