DROP TABLE IF EXISTS aa CASCADE
DROP TABLE IF EXISTS ab CASCADE
CREATE TABLE aa (id int PRIMARY KEY, v int, s text)
CREATE TABLE ab (id int PRIMARY KEY)
INSERT INTO aa VALUES (1,5,'p'),(2,NULL,NULL),(3,7,'q')
INSERT INTO ab VALUES (1),(2),(3)
