# reference-version: 15
# jsonpath keyvalue() ids by POSITION (equal objects in different containers),
# to_date / to_timestamp error codes and DETAIL lines, text search casing.
select to_tsvector('simple', 'ÉCOLE Straße ÅNGSTRÖM')
select to_date('2020-13-01', 'YYYY-MM-DD')
select to_date('2020-02-30', 'YYYY-MM-DD')
select to_date('abc', 'YYYY')
select to_timestamp('2020-01-01 25:00', 'YYYY-MM-DD HH24:MI')
select to_date('32', 'DD')
select to_timestamp('99', 'MI')
select to_date('2020-00-10', 'YYYY-MM-DD')
select to_date('1 2', 'DDD YYYY')
select jsonb_path_query('{"a": {"b": 1}, "c": {"b": 1}}', '$.*.keyvalue()')
select jsonb_path_query('[{"a": 1}, {"a": 1}]', '$[*].keyvalue()')
select jsonb_path_query('{"x": [{"a": 1}], "y": {"z": {"a": 2}}}', '$.**.keyvalue()')
select to_date('xyz 2020', 'Mon YYYY')
select to_timestamp('2020 xm', 'YYYY AM')
select to_date('2020 Fooday', 'YYYY Day')
select jsonb_path_query('{"a": {"b": 1}, "c": {"b": 1}}', '$.*.keyvalue()')
select jsonb_path_query('[{"a": 1}, {"a": 1}]', '$[*].keyvalue()')
select jsonb_path_query('{"x": [{"a": 1}], "y": {"z": {"a": 1}}}', '$.**.keyvalue()')
select jsonb_path_query('{"c": {"b": 1}, "a": {"b": 1}}', '$.c.keyvalue()')
select jsonb_path_query('[{"a": 1}, {"a": 1}, {"a": 1}]', '$[2].keyvalue()')
select jsonb_path_query('[{"a": 1}, {"a": 2}, {"a": 1}]', '$[*] ? (@.a == 1).keyvalue()')
select jsonb_path_query('{"a": [{"k": 1}, {"k": 1}]}', 'lax $.a.keyvalue()')
