DROP SEQUENCE IF EXISTS b39_s
CREATE SEQUENCE b39_s
DROP TABLE IF EXISTS b39_m
CREATE TABLE b39_m (m money)
INSERT INTO b39_m VALUES ('1.5')
DROP TABLE IF EXISTS b39_lt
CREATE TABLE b39_lt (i int)
CREATE OR REPLACE FUNCTION b39_lk() RETURNS int LANGUAGE plpgsql AS 'BEGIN LOCK TABLE b39_lt IN ACCESS EXCLUSIVE MODE; RETURN 1; END'
CREATE OR REPLACE FUNCTION b39_args(a int, b text) RETURNS text LANGUAGE plpgsql AS 'BEGIN RETURN $2 || $1::text || a; END'
DROP TABLE IF EXISTS b39_ins_t
CREATE TABLE b39_ins_t (id int)
CREATE OR REPLACE FUNCTION b39_ins(int) RETURNS int AS 'BEGIN INSERT INTO b39_ins_t(id) VALUES ($1); RETURN 1; END;' LANGUAGE plpgsql
