DROP TABLE IF EXISTS b41d
DROP TABLE IF EXISTS b41e
DROP TABLE IF EXISTS b41h
CREATE TABLE b41d ("a.b" int, "$c" int, n int)
INSERT INTO b41d VALUES (1, 1, 1), (2, 2, 2)
CREATE TABLE b41e ("x.y" int UNIQUE NULLS NOT DISTINCT)
CREATE TABLE b41h ("p.q" text, s text, n int)
INSERT INTO b41h VALUES (NULL, NULL, 1)
