DROP SCHEMA IF EXISTS b41a CASCADE
DROP SCHEMA IF EXISTS b41b CASCADE
DROP TABLE IF EXISTS b41f
DROP TABLE IF EXISTS b41g
DROP ROLE IF EXISTS b41r
CREATE SCHEMA b41a
CREATE SCHEMA b41b
CREATE TABLE b41a.t (a int, b text)
CREATE TABLE b41b.t (a int)
CREATE SEQUENCE b41a.q
CREATE INDEX b41ix ON b41a.t (a)
CREATE INDEX b41ix ON b41b.t (a)
CREATE ROLE b41r
CREATE TABLE b41f (g int, a int, s text)
INSERT INTO b41f VALUES (1, 1, 'x'), (1, 2, NULL), (2, 3, 'y'), (2, NULL, 'z'), (3, 5, 'w')
CREATE TABLE b41g (k int)
INSERT INTO b41g VALUES (1), (3), (5)
