DROP SCHEMA IF EXISTS b41a CASCADE
DROP SCHEMA IF EXISTS b41b CASCADE
DROP TABLE IF EXISTS b41x
DROP VIEW IF EXISTS b41vv
DROP ROLE IF EXISTS b41r
DROP ROLE IF EXISTS b41grp
CREATE SCHEMA b41a
CREATE SCHEMA b41b
CREATE TABLE b41a.t (a int)
CREATE TABLE b41b.t (a int)
CREATE TABLE b41x (a int)
CREATE VIEW b41vv AS SELECT a FROM b41x
CREATE ROLE b41r
CREATE ROLE b41grp
