DROP SCHEMA IF EXISTS b42s CASCADE
DROP TABLE IF EXISTS b42t
DROP SEQUENCE IF EXISTS b42q
DROP FUNCTION IF EXISTS b42f()
DROP ROLE IF EXISTS b42r
DROP ROLE IF EXISTS b42g
CREATE ROLE b42r
CREATE ROLE b42g
CREATE SCHEMA b42s
CREATE TABLE b42s.t (a int, b int)
INSERT INTO b42s.t VALUES (1, 2)
CREATE TABLE b42t (a int, b int)
CREATE SEQUENCE b42s.q
CREATE SEQUENCE b42q
CREATE FUNCTION b42f() RETURNS int LANGUAGE sql AS 'select 1'
