DROP SCHEMA IF EXISTS b43s CASCADE
DROP SCHEMA IF EXISTS b43fs CASCADE
DROP FUNCTION IF EXISTS b43f(int)
DROP FUNCTION IF EXISTS b43f(text)
DROP SEQUENCE IF EXISTS b43q
DROP ROLE IF EXISTS b43r
CREATE ROLE b43r
CREATE SCHEMA b43s
CREATE SCHEMA b43fs
CREATE TABLE b43s.t (a int)
CREATE TABLE b43s.only_s (a int)
GRANT SELECT ON ALL TABLES IN SCHEMA b43s TO b43r
CREATE SEQUENCE b43q
CREATE SEQUENCE b43s.q2
CREATE FUNCTION b43f(int) RETURNS int LANGUAGE sql AS 'select 1'
CREATE FUNCTION b43f(text) RETURNS int LANGUAGE sql AS 'select 2'
CREATE FUNCTION b43fs.g() RETURNS int LANGUAGE sql AS 'select 3'
