DROP TABLE IF EXISTS b44sp
DROP TABLE IF EXISTS b44ip
DROP FUNCTION IF EXISTS b44tf() CASCADE
DROP ROLE IF EXISTS b44r
CREATE ROLE b44r
CREATE TABLE b44sp (id serial, v int)
CREATE TABLE b44ip (id int GENERATED ALWAYS AS IDENTITY, v int)
GRANT INSERT, SELECT ON b44sp, b44ip TO b44r
GRANT TRIGGER ON b44sp TO b44r
CREATE FUNCTION b44tf() RETURNS trigger LANGUAGE plpgsql AS 'begin return new; end'
REVOKE EXECUTE ON FUNCTION b44tf() FROM PUBLIC
