DROP TABLE IF EXISTS b45bt
DROP ROLE IF EXISTS b45r
CREATE ROLE b45r
CREATE TABLE b45bt (i int, n numeric, t text)
INSERT INTO b45bt VALUES (-1, -1.5, 'ab')
GRANT SELECT, UPDATE, DELETE ON b45bt TO b45r
