# reference-version: 15
# Batch 46: ruleutils prints the implicit casts of the overload a call
# resolves to (to_char over a date), EXTRACT as its syntax, and the int
# wrap-column form of pg_get_viewdef wraps by width.
SELECT pg_get_viewdef('b46v1'::regclass)
SELECT pg_get_viewdef('b46v1'::regclass, true)
SELECT pg_get_viewdef('b46v1'::regclass, -1)
SELECT pg_get_viewdef('b46v1'::regclass, 0)
SELECT pg_get_viewdef('b46v1'::regclass, 30)
SELECT pg_get_viewdef('b46v1'::regclass, 60)
SELECT pg_get_viewdef('b46v1'::regclass, 80)
SELECT pg_get_viewdef('b46v1'::regclass, 200)
SELECT pg_get_viewdef('b46v2'::regclass)
SELECT pg_get_viewdef('b46v2'::regclass, true)
SELECT pg_get_viewdef('b46v2'::regclass, -1)
SELECT pg_get_viewdef('b46v2'::regclass, 0)
SELECT pg_get_viewdef('b46v2'::regclass, 30)
SELECT pg_get_viewdef('b46v2'::regclass, 60)
SELECT pg_get_viewdef('b46v2'::regclass, 80)
SELECT pg_get_viewdef('b46v2'::regclass, 200)
SELECT pg_get_viewdef('b46v3'::regclass)
SELECT pg_get_viewdef('b46v3'::regclass, true)
SELECT pg_get_viewdef('b46v3'::regclass, -1)
SELECT pg_get_viewdef('b46v3'::regclass, 0)
SELECT pg_get_viewdef('b46v3'::regclass, 30)
SELECT pg_get_viewdef('b46v3'::regclass, 60)
SELECT pg_get_viewdef('b46v3'::regclass, 80)
SELECT pg_get_viewdef('b46v3'::regclass, 200)
SELECT pg_get_viewdef('b46v4'::regclass)
SELECT pg_get_viewdef('b46v4'::regclass, true)
SELECT pg_get_viewdef('b46v4'::regclass, -1)
SELECT pg_get_viewdef('b46v4'::regclass, 0)
SELECT pg_get_viewdef('b46v4'::regclass, 30)
SELECT pg_get_viewdef('b46v4'::regclass, 60)
SELECT pg_get_viewdef('b46v4'::regclass, 80)
SELECT pg_get_viewdef('b46v4'::regclass, 200)
SELECT pg_get_viewdef('b46v5'::regclass)
SELECT pg_get_viewdef('b46v5'::regclass, true)
SELECT pg_get_viewdef('b46v5'::regclass, -1)
SELECT pg_get_viewdef('b46v5'::regclass, 0)
SELECT pg_get_viewdef('b46v5'::regclass, 30)
SELECT pg_get_viewdef('b46v5'::regclass, 60)
SELECT pg_get_viewdef('b46v5'::regclass, 80)
SELECT pg_get_viewdef('b46v5'::regclass, 200)
SELECT viewname, definition FROM pg_views WHERE viewname LIKE 'b46v%' ORDER BY 1
