DROP TABLE IF EXISTS b48t CASCADE
DROP FUNCTION IF EXISTS b48tf() CASCADE
DROP TYPE IF EXISTS b48e
CREATE TYPE b48e AS ENUM ('a', 'b')
CREATE TABLE b48t (id int PRIMARY KEY, name text, e b48e)
CREATE FUNCTION b48tf() RETURNS trigger LANGUAGE plpgsql AS 'begin return new; end'
CREATE TRIGGER b48trg BEFORE INSERT ON b48t FOR EACH ROW EXECUTE FUNCTION b48tf()
