select pg_get_viewdef('b50v1'::regclass);
select pg_get_viewdef('b50v2'::regclass);
select pg_get_viewdef('b50v3'::regclass);
select pg_get_viewdef('b50v4'::regclass);
select pg_get_viewdef('b50v5'::regclass);
select pg_get_viewdef('b50v6'::regclass);
select pg_get_viewdef('b50v7'::regclass);
select pg_get_viewdef('b50v8'::regclass);
select pg_get_viewdef('b50v9'::regclass);
select pg_get_viewdef('b50v10'::regclass);
select pg_get_viewdef('b50v11'::regclass);
select pg_get_viewdef('b50v12'::regclass);
select pg_get_viewdef('b50v13'::regclass);
select pg_get_viewdef('b50v14'::regclass);
select pg_get_viewdef('b50v15'::regclass);
select pg_get_viewdef('b50v16'::regclass);
select pg_get_viewdef('b50v17'::regclass);
select pg_get_viewdef('b50v18'::regclass);
select pg_get_viewdef('b50v19'::regclass);
select pg_get_viewdef('b50v20'::regclass);
select pg_get_viewdef('b50v1'::regclass, true);
select pg_get_viewdef('b50v1'::regclass, 40);
select pg_get_viewdef('b50v2'::regclass, true);
select pg_get_viewdef('b50v2'::regclass, 40);
select pg_get_viewdef('b50v3'::regclass, true);
select pg_get_viewdef('b50v3'::regclass, 40);
select pg_get_viewdef('b50v4'::regclass, true);
select pg_get_viewdef('b50v4'::regclass, 40);
select pg_get_viewdef('b50v5'::regclass, true);
select pg_get_viewdef('b50v5'::regclass, 40);
select pg_get_viewdef('b50v6'::regclass, true);
select pg_get_viewdef('b50v6'::regclass, 40);
select pg_get_viewdef('b50v7'::regclass, true);
select pg_get_viewdef('b50v7'::regclass, 40);
select pg_get_viewdef('b50v8'::regclass, true);
select pg_get_viewdef('b50v8'::regclass, 40);
select pg_get_viewdef('b50v9'::regclass, true);
select pg_get_viewdef('b50v9'::regclass, 40);
select pg_get_viewdef('b50v10'::regclass, true);
select pg_get_viewdef('b50v10'::regclass, 40);
select pg_get_viewdef('b50v11'::regclass, true);
select pg_get_viewdef('b50v11'::regclass, 40);
select pg_get_viewdef('b50v12'::regclass, true);
select pg_get_viewdef('b50v12'::regclass, 40);
select pg_get_viewdef('b50v13'::regclass, true);
select pg_get_viewdef('b50v13'::regclass, 40);
select pg_get_viewdef('b50v14'::regclass, true);
select pg_get_viewdef('b50v14'::regclass, 40);
select pg_get_viewdef('b50v15'::regclass, true);
select pg_get_viewdef('b50v15'::regclass, 40);
select pg_get_viewdef('b50v16'::regclass, true);
select pg_get_viewdef('b50v16'::regclass, 40);
select pg_get_viewdef('b50v17'::regclass, true);
select pg_get_viewdef('b50v17'::regclass, 40);
select pg_get_viewdef('b50v18'::regclass, true);
select pg_get_viewdef('b50v18'::regclass, 40);
select pg_get_viewdef('b50v19'::regclass, true);
select pg_get_viewdef('b50v19'::regclass, 40);
select pg_get_viewdef('b50v20'::regclass, true);
select pg_get_viewdef('b50v20'::regclass, 40);
select pg_get_viewdef('b50w1'::regclass);
select pg_get_viewdef('b50w1'::regclass, true);
select pg_get_viewdef('b50w2'::regclass);
select pg_get_viewdef('b50w2'::regclass, true);
select pg_get_viewdef('b50w3'::regclass);
select pg_get_viewdef('b50w3'::regclass, true);
select pg_get_viewdef('b50w4'::regclass);
select pg_get_viewdef('b50w4'::regclass, true);
select pg_get_viewdef('b50w5'::regclass);
select pg_get_viewdef('b50w5'::regclass, true);
select pg_get_viewdef('b50w6'::regclass);
select pg_get_viewdef('b50w6'::regclass, true);
select pg_get_viewdef('b50w7'::regclass);
select pg_get_viewdef('b50w7'::regclass, true);
select pg_get_viewdef('b50w8'::regclass);
select pg_get_viewdef('b50w8'::regclass, true);
select pg_get_viewdef('b50w9'::regclass);
select pg_get_viewdef('b50w9'::regclass, true);
select pg_get_viewdef('b50w10'::regclass);
select pg_get_viewdef('b50w10'::regclass, true);
select pg_get_viewdef('b50w11'::regclass);
select pg_get_viewdef('b50w11'::regclass, true);
select pg_get_viewdef('b50w12'::regclass);
select pg_get_viewdef('b50w12'::regclass, true);
select pg_get_viewdef('b50w13'::regclass);
select pg_get_viewdef('b50w13'::regclass, true);
select pg_get_viewdef('b50w14'::regclass);
select pg_get_viewdef('b50w14'::regclass, true);
select pg_get_viewdef('b50w15'::regclass);
select pg_get_viewdef('b50w15'::regclass, true);
select pg_get_viewdef('b50w16'::regclass);
select pg_get_viewdef('b50w16'::regclass, true);
select pg_get_viewdef('b50w17'::regclass);
select pg_get_viewdef('b50w17'::regclass, true);
select pg_get_viewdef('b50w18'::regclass);
select pg_get_viewdef('b50w18'::regclass, true);
select pg_get_viewdef('b50w19'::regclass);
select pg_get_viewdef('b50w19'::regclass, true);
select pg_get_viewdef('b50w20'::regclass);
select pg_get_viewdef('b50w20'::regclass, true);
select pg_get_viewdef('b50w21'::regclass);
select pg_get_viewdef('b50w21'::regclass, true);
select pg_get_viewdef('b50w22'::regclass);
select pg_get_viewdef('b50w22'::regclass, true);
select pg_get_viewdef('b50w23'::regclass);
select pg_get_viewdef('b50w23'::regclass, true);
select pg_get_viewdef('b50w24'::regclass);
select pg_get_viewdef('b50w24'::regclass, true);
select pg_get_viewdef('b50x1'::regclass);
select pg_get_viewdef('b50x1'::regclass, true);
select pg_get_viewdef('b50x2'::regclass);
select pg_get_viewdef('b50x2'::regclass, true);
select pg_get_viewdef('b50x3'::regclass);
select pg_get_viewdef('b50x3'::regclass, true);
select pg_get_viewdef('b50x4'::regclass);
select pg_get_viewdef('b50x4'::regclass, true);
select pg_get_viewdef('b50x5'::regclass);
select pg_get_viewdef('b50x5'::regclass, true);
select pg_get_viewdef('b50x6'::regclass);
select pg_get_viewdef('b50x6'::regclass, true);
select pg_get_viewdef('b50x7'::regclass);
select pg_get_viewdef('b50x7'::regclass, true);
select pg_get_viewdef('b50x8'::regclass);
select pg_get_viewdef('b50x8'::regclass, true);
select pg_get_viewdef('b50x9'::regclass);
select pg_get_viewdef('b50x9'::regclass, true);
select pg_get_viewdef('b50x10'::regclass);
select pg_get_viewdef('b50x10'::regclass, true);
select pg_get_viewdef('b50x11'::regclass);
select pg_get_viewdef('b50x11'::regclass, true);
select pg_get_viewdef('b50x12'::regclass);
select pg_get_viewdef('b50x12'::regclass, true);
select pg_get_viewdef('b50x13'::regclass);
select pg_get_viewdef('b50x13'::regclass, true);
select pg_get_viewdef('b50x14'::regclass);
select pg_get_viewdef('b50x14'::regclass, true);
select pg_get_viewdef('b50x15'::regclass);
select pg_get_viewdef('b50x15'::regclass, true);
select pg_get_viewdef('b50x16'::regclass);
select pg_get_viewdef('b50x16'::regclass, true);
