DROP VIEW IF EXISTS b50v1, b50v2, b50v3, b50v4, b50v5, b50v6, b50v7, b50v8, b50v9, b50v10, b50v11, b50v12, b50v13, b50v14, b50v15, b50v16, b50v17, b50v18, b50v19, b50v20;
DROP TABLE IF EXISTS b50_vt, b50_vu;
create table b50_vt (id int primary key, a int, b text, c numeric(10,2), d date, j jsonb, arr int[], f float8, flag bool);
create table b50_vu (id int primary key, tid int, w text);
create view b50v1 as select id, case when a > 1 then 'big' when a is null then null else 'small' end as k from b50_vt;
create view b50v2 as select id, coalesce(b, 'none') as b, nullif(a, 0) as n, greatest(a, 5) as g from b50_vt;
create view b50v3 as select id from b50_vt where a in (select tid from b50_vu) and exists (select 1 from b50_vu u where u.tid = b50_vt.id);
create view b50v4 as select id, row_number() over (partition by a order by id desc) as rn, sum(f) over (order by id rows between 1 preceding and current row) as s from b50_vt;
create view b50v5 as select a, count(*) filter (where flag) as n, array_agg(b order by id) as bs, string_agg(b, ',') as s from b50_vt group by a having count(*) > 1;
create view b50v6 as select id, upper(b) as u, substring(b from 2 for 3) as s, b || '-' || a as cat, length(b) as l, trim(both 'x' from b) as t from b50_vt;
create view b50v7 as select id, a::text as at, c::int as ci, d + 1 as tomorrow, d - interval '1 day' as yest, extract(year from d) as y from b50_vt;
create view b50v8 as select id, arr[1] as first, arr || 4 as more, 3 = any(arr) as has3, array_length(arr, 1) as n from b50_vt;
create view b50v9 as select id, j -> 'k' as k, j ->> 'k' as ks, j #> '{a,b}' as p, j ? 'k' as hk, j @> '{"k":1}' as c from b50_vt;
create view b50v10 as select id from b50_vt where b like 'a%' and b not ilike '%z' and a between 1 and 10 and a is distinct from 3 and b ~ '^x';
create view b50v11 as select id from b50_vt where (a, b) = (1, 'x') or (a, b) > (2, 'y');
create view b50v12 as select distinct on (a) a, id from b50_vt order by a, id desc nulls last limit 10 offset 2;
create view b50v13 as select id from b50_vt union select tid from b50_vu except select 0 order by 1;
create view b50v14 as with x as (select id, a from b50_vt where a > 0) select x.id, u.w from x join b50_vu u on u.tid = x.id;
create view b50v15 as select t.id, u.w from b50_vt t left join b50_vu u using (id) where u.w is not null;
create view b50v16 as select id, (select max(w) from b50_vu where tid = b50_vt.id) as mw, a % 3 as m, -a as neg, @ a as ab, f ^ 2 as sq from b50_vt;
create view b50v17 as select id, flag and a > 1 as x, not flag as nf, flag is true as ft, b is not null as hb from b50_vt;
create view b50v18 as select id, now() - d::timestamp as age, current_date as cd, date_trunc('month', d) as m, to_char(d, 'YYYY') as y from b50_vt;
create view b50v19 as select id, round(c, 1) as r, abs(a) as ab, a / 2 as half, c * 2.5 as dbl, f::numeric(5,1) as fn from b50_vt;
create view b50v20 as select count(distinct a) as da, avg(c) as av, min(d) as mn, bool_and(flag) as al, percentile_cont(0.5) within group (order by f) as med from b50_vt;
DROP VIEW IF EXISTS b50w1, b50w2, b50w3, b50w4, b50w5, b50w6, b50w7, b50w8, b50w9, b50w10, b50w11, b50w12, b50w13, b50w14, b50w15, b50w16, b50w17, b50w18, b50w19, b50w20, b50w21, b50w22, b50w23, b50w24;
DROP TABLE IF EXISTS b50_wt, b50_wu;
create table b50_wt (id int primary key, a int, b text, v varchar(20), c numeric(10,2), d date, ts timestamp, j jsonb, arr int[], f float8, flag bool, i interval);
create table b50_wu (id int primary key, tid int, w text);
create view b50w1 as select a, b, count(*) from b50_wt group by grouping sets ((a), (b), ());
create view b50w2 as select a, sum(c) from b50_wt group by rollup (a);
create view b50w3 as select t.id, x.w from b50_wt t, lateral (select w from b50_wu u where u.tid = t.id limit 1) x;
create view b50w4 as select * from (values (1, 'a'), (2, 'b')) as v(n, s);
create view b50w5 as select g from generate_series(1, 10) g;
create view b50w6 as select id from b50_wt where v in ('a', 'b') and b not in ('x');
create view b50w7 as select id from b50_wt where a not in (select tid from b50_wu) and a > all (select tid from b50_wu);
create view b50w8 as select id, case a when 1 then 'one' when 2 then 'two' end as n from b50_wt;
create view b50w9 as select id, jsonb_build_object('a', a, 'b', b) as o, to_jsonb(b) as tb, jsonb_array_length(j) as n from b50_wt;
create view b50w10 as select id, array(select tid from b50_wu where tid = b50_wt.id) as tids from b50_wt;
create view b50w11 as select id, i * 2 as i2, ts + i as later, ts - interval '1 hour' as before, age(ts) as age from b50_wt;
create view b50w12 as select id from b50_wt where b similar to 'a%' and b ~* 'x' and b like 'a!%' escape '!';
create view b50w13 as select id from b50_wt where a between symmetric 1 and 10;
create view b50w14 as select id, position('x' in b) as p, overlay(b placing 'y' from 1 for 1) as o, strpos(b, 'z') as s from b50_wt;
create view b50w15 as select id, sum(a) over w as s, rank() over w as r from b50_wt window w as (partition by b order by id);
create view b50w16 as select distinct a, b from b50_wt where flag;
create view b50w17 as select id, a::bigint + 1 as big, c::float8 as cf, v || 'x' as vx, length(v) as lv from b50_wt;
create view b50w18 as select id, coalesce((select max(tid) from b50_wu), 0) as m, exists(select 1 from b50_wu) as e from b50_wt;
create view b50w19 as with recursive r(n) as (select 1 union all select n + 1 from r where n < 5) select n from r;
create view b50w20 as select id, arr[1:2] as sl, array_append(arr, 9) as ap, cardinality(arr) as cnt, arr @> array[1] as has from b50_wt;
create view b50w21 as select id, round(f::numeric, 2) as r, f::int as fi, -f as nf, abs(c) as ac from b50_wt;
create view b50w22 as select a, avg(f) filter (where a > 0) as av, max(d) as md from b50_wt group by a order by a desc nulls last;
create view b50w23 as select id, b is not distinct from 'x' as nd, flag is not false as nf, not (a > 1) as na from b50_wt;
create view b50w24 as select id, date_part('year', d) as y, d::timestamptz as dt, now()::date as today, extract(epoch from ts) as ep from b50_wt;
DROP VIEW IF EXISTS b50x1, b50x2, b50x3, b50x4, b50x5, b50x6, b50x7, b50x8, b50x9, b50x10, b50x11, b50x12, b50x13, b50x14, b50x15, b50x16;
DROP TABLE IF EXISTS b50_xt;
create table b50_xt (id int primary key, a int, b text, c numeric, d date, ts timestamptz, j json, u uuid, arr text[], flag bool, bi bigint, sm smallint);
create view b50x1 as select id, a::numeric / 3 as q, bi + a as s, sm * 2 as m, a::float8 / 2 as f from b50_xt;
create view b50x2 as select id, j -> 'k' as k, j ->> 0 as z, u::text as us from b50_xt;
create view b50x3 as select id, arr[1] || 'x' as a1, array_to_string(arr, ',') as s, 'x' = any(arr) as h from b50_xt;
create view b50x4 as select id, b || ts as bt, ts at time zone 'UTC' as utc, date_trunc('day', ts) as day from b50_xt;
create view b50x5 as select id, case when flag then a end as x, coalesce(sm, bi) as cb, nullif(b, '') as nb from b50_xt;
create view b50x6 as select id, lag(a) over (order by id) as la, first_value(b) over (partition by flag order by d rows unbounded preceding) as fv from b50_xt;
create view b50x7 as select id from b50_xt t where exists (select 1 from b50_xt t2 where t2.a = t.id and t2.b like t.b || '%');
create view b50x8 as select a, count(*) as n from b50_xt group by a having count(*) between 2 and 5 order by n desc;
create view b50x9 as select id, substr(b, 1, 3) as s3, left(b, 2) as l2, replace(b, 'a', 'b') as r, lower(b) || upper(b) as lu from b50_xt;
create view b50x10 as select id, extract(dow from ts) as dow, ts::date as d2, d + 7 as nd, age(d::timestamp, '2020-01-01') as ag from b50_xt;
create view b50x12 as select id, a in (1, 2, 3) as in3, b not in ('x', 'y') as nin, sm in (1, 2) as sin from b50_xt;
create view b50x13 as select id, cast(a as text) as t, a::varchar(5) as v, c::numeric(5,2) as n, b::char(3) as ch from b50_xt;
create view b50x14 as select id, greatest(a, sm, bi) as g, least(c, 1.5) as l from b50_xt;
create view b50x15 as select distinct on (b) b, id, d from b50_xt order by b, d desc;
create view b50x16 as select id, now() as n, current_timestamp as ct, localtimestamp as lt, current_user as cu, session_user as su from b50_xt;
