select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.s > o.s) order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.s < o.s) order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.s <> o.s) order by 1;
select id from b50_o o where not exists (select 1 from b50_t t where t.x = o.a and t.s >= o.s) order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.v > o.v) order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.nm > o.nm) order by 1;
select id, (select count(*) from b50_t t where t.x = o.a and t.s <= o.s) from b50_o o order by 1;
select id, (select t.s from b50_t t where t.x = o.a and t.s > o.s limit 1) from b50_o o order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.x = o.a and t.iv > interval '1 hour') order by 1;
select id from b50_o o where exists (select 1 from b50_t t join b50_u u on u.tid = t.id where t.x = o.a) order by 1;
select id from b50_o o where exists (select 1 from b50_t t left join b50_u u on u.tid = t.id where t.x = o.a and u.w is null) order by 1;
select id from b50_o o where not exists (select 1 from b50_t t join b50_u u on u.tid = t.id where t.x = o.a) order by 1;
select id, (select count(*) from b50_t t join b50_u u on u.tid = t.id where t.x = o.a) from b50_o o order by 1;
select id, (select count(*) from b50_t t, b50_u u where u.tid = t.id and t.x = o.a) from b50_o o order by 1;
select id from b50_o o where exists (select 1 from b50_t t where t.n = o.n) order by 1;
select id from b50_o o where not exists (select 1 from b50_t t where t.n = o.n) order by 1;
select id, (select count(*) from b50_t t where t.n = o.n) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.n = o.n and t.x = o.a) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.f = o.n) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.n = o.f) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.n = o.a) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.x = o.n) from b50_o o order by 1;
select id from b50_o o where o.n in (select n from b50_t) order by 1;
select id from b50_o o where o.n not in (select n from b50_t where n is not null) order by 1;
select id from b50_o o where o.n not in (select n from b50_t) order by 1;
select id from b50_o where n in (1.5, 2, 0.1, 'NaN') order by 1;
select id from b50_o where n not in (1.5, 2) order by 1;
select id from b50_o where n in (100000000000000000000000000000000000000.5, 1.50) order by 1;
select id from b50_o where n not in (100000000000000000000000000000000000000.5, 'NaN') order by 1;
select id from b50_o where n = any(array[1.5, 2.00]) order by 1;
select id from b50_o where n <> all(array[1.5, 2.00, 0.1]) order by 1;
select id from b50_o where n = any(array[1.5, null]) order by 1;
select id from b50_o where n <> all(array[1.5, null]) order by 1;
select id from b50_o where n in (2, 3) order by 1;
select id from b50_o where n in (null, 1.5) order by 1;
select id from b50_o where n not in (null, 1.5) order by 1;
select id, (select max(t.y) from b50_t t where t.x = o.a and t.id > o.id) from b50_o o order by 1;
select id, (select min(t.s) from b50_t t where t.x = o.a and t.y > 15) from b50_o o order by 1;
select id, (select min(t.s) from b50_t t where t.x = o.a and t.s > o.s) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.x = o.a and t.f > o.f) from b50_o o order by 1;
select id, (select count(t.n) from b50_t t where t.x = o.a and t.y >= o.id * 10) from b50_o o order by 1;
select id, (select max(t.f) from b50_t t where t.x = o.a and t.y <> 20) from b50_o o order by 1;
select id, (select max(t.n) from b50_t t where t.x = o.a and t.y > 0) from b50_o o order by 1;
select id, (select count(*) from b50_t t where t.x = o.a and t.y > null::int) from b50_o o order by 1;
select id, (select max(t.iv) from b50_t t where t.x = o.a and t.y > 0) from b50_o o order by 1;
select id from b50_o o where (select count(*) from b50_t t where t.x = o.a and t.y < o.id * 20) > 1 order by 1;
