select b50_f(0);
select b50_f(a - 1) from b50_ft;
select b50_f(abs(0));
select b50_f(length(''));
select a from b50_ft where b = a;
select a from b50_ft where b = a and a = b;
select a from b50_ft where a = b or b = a;
select a, a from b50_ft where a = 'x';
select b from b50_ft where b + 1 = 2;
select b || a from b50_ft where (b || a) > 1;
select coalesce(a, b) from b50_ft;
select case when a = 1 then b else a end from b50_ft;
select greatest(a, b) from b50_ft;
select a from b50_ft where a in (select b from b50_ft);
select a from b50_ft where (a, b) = (1, 2);
select a from b50_ft where a between b and 3;
select a from b50_ft where d > 1;
select a from b50_ft where j > 1;
select a from b50_ft where arr > 1;
select a from b50_ft where ts = 1;
select a from b50_ft where c = 'abc';
select a from b50_ft where a = 1.5::numeric and b = 1;
select nullif(a, b) from b50_ft;
select a from b50_ft where a is distinct from b;
select a from b50_ft where b like a;
select a from b50_ft order by a + b;
select a from b50_ft group by a having max(b) > 1;
select sum(b) from b50_ft;
select a from b50_ft where not b;
select a from b50_ft where b and a = 1;
select -b from b50_ft;
select a from b50_ft where abs(b) > 1;
select a from b50_ft where a = any(array['x']);
select a::text = b from b50_ft where a = b;
select b50_ft.zz from b50_ft;
select zz from b50_ft where zz = 1;
select a from b50_ft x where b50_ft.a = 1;
select b50_f(abs(-0) * 1) from b50_ft;
select b50_f(random()::int * 0);
select b50_g(1) / b50_f(0);
select a, a from b50_ft where a = 'x';
select a from b50_ft where a = 1 and a = 'x';
select b from b50_ft where b = 'x' and b = 1;
select a + 1, a + b from b50_ft;
select zz, a from b50_ft;
select a from b50_ft where a = 1 order by zz;
select a from b50_ft where a = 1 group by a having zz > 1;
select a from b50_ft x join b50_ft y on x.a = y.zz;
select a from b50_ft x join b50_ft y on x.a = y.a;
select x.a from b50_ft x join b50_ft y on x.a = y.b;
select coalesce(a, c) from b50_ft;
select coalesce(c, a, 'x') from b50_ft;
select case when true then 1 else 'x' end;
select case when true then 1 when false then 2.5 else b end from b50_ft;
select greatest(d, ts) from b50_ft;
select least(a, d) from b50_ft;
select coalesce(a::text, b) from b50_ft;
select a from b50_ft where a not in (select b from b50_ft);
select a from b50_ft where a = any(select b from b50_ft);
select a from b50_ft where a > all(select c from b50_ft);
select a from b50_ft where not a;
select a from b50_ft where a = 1 or b;
select a from b50_ft where (a = 1) is distinct from b;
select +b from b50_ft;
select -d from b50_ft;
select -j from b50_ft;
select pg_collation_for(n), pg_collation_for(t) from b50_names;
select greatest(date '2020-01-02', timestamptz '2020-01-01 10:00+00')::text, pg_typeof(least(date '2020-01-02', timestamp '2020-01-01 10:00'));
create view b50_rec as select row(1, 2) as r;
select 'b50_nosuch'::regclass;
select 'public.b50_nosuch'::regclass;
