select pg_collation_for(1);
select pg_collation_for('a');
select pg_collation_for('a'::text);
select pg_collation_for(null);
select pg_collation_for(now());
select pg_collation_for(null::int);
select pg_collation_for(array['a']);
select collation for ('a');
select pg_collation_for(x) from (values ('a')) v(x);
select pg_collation_for(x) from (values (1)) v(x);
select pg_collation_for(i) from b52c;
select pg_collation_for(t), pg_collation_for(n), pg_collation_for(c), collation for (t) from (select 1) s, b52c;
select pg_collation_for(ts) from b52c;
select pg_collation_for(i::text) from b52c;
select pg_collation_for(1.5);
select pg_collation_for(true);
select pg_collation_for(1+1);
select pg_collation_for(lower('a'));
select pg_collation_for('a' || 'b');
select pg_collation_for('{}'::jsonb);
select pg_collation_for(x) from (values (null)) v(x);
