select id from b52_o o where exists (select 1 from b52_t t where t.x = o.a and exists (select 1 from b52_u u where u.tid = t.id and u.id > o.b)) order by 1;
select id from b52_o o where not exists (select 1 from b52_t t where t.x = o.a and exists (select 1 from b52_u u where u.tid = t.id and u.id > o.b)) order by 1;
select id, (select count(*) from b52_t t where t.x = o.a and exists (select 1 from b52_u u where u.tid = t.id and u.id >= o.id)) from b52_o o order by 1;
select id from b52_o o where exists (select 1 from b52_t t where t.x = o.a and t.y > 2 and exists (select 1 from b52_u u where u.tid = t.id)) order by 1;
select id from b52_o o where exists (select 1 from b52_t t where t.x = o.a and (t.y > o.b or t.v is null)) order by 1;
select count(*) from b52_t where x = 1 and exists (select 1 from b52_u u where u.tid = b52_t.id);
select count(*) from b52_t where x = 1 and (case when y > 2 then true else false end);
select count(*) from b52_t where x = 1 and y / (y - 3) > 0;
select id, (select sum(v) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, (select avg(v) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, (select sum(sm) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, (select avg(sm) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, (select sum(bi) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, (select avg(bi) from b52_t t where t.x = o.a and t.y > o.b) from b52_o o order by 1;
select id, pg_typeof((select sum(v) from b52_t t where t.x = o.a and t.y > o.b)), pg_typeof((select avg(sm) from b52_t t where t.x = o.a and t.y > o.b)) from b52_o o order by 1;
select id, (select v from b52_t t where t.x = o.a order by y desc, v limit 1) from b52_o o order by 1;
select id, (select v from b52_t t where t.x = o.a order by y desc nulls last, v limit 1 offset 1) from b52_o o order by 1;
select id, (select s from b52_t t where t.x = o.a order by s limit 1) from b52_o o order by 1;
select id, (select s from b52_t t where t.x = o.a and t.y > o.b order by s desc limit 1) from b52_o o order by 1;
select id, array(select v from b52_t t where t.x = o.a order by v nulls first) from b52_o o order by 1;
select id, array(select t.id from b52_t t where t.x = o.a order by 1 desc) from b52_o o order by 1;
select id, (select v from b52_t t where t.x = o.a order by y + o.b, v limit 1) from b52_o o order by 1;
select b52_f(1), b52_f(1);
select b52_f(2), b52_f(3), b52_f(-5);
