select id, (select sum(bi) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select avg(bi) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select sum(nu) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select avg(nu) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select sum(nf) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select avg(nf) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select sum(fl) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select avg(fl) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select sum(re) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select avg(re) from b53_t t where t.x = o.a and t.y > o.b) from b53_o o order by 1;
select id, (select sum(bi) from b53_t t where t.x = o.a and t.y >= o.b and t.y < o.b + 3) from b53_o o order by 1;
select id, (select avg(nu) from b53_t t where t.x = o.a and t.y <= o.b + 2) from b53_o o order by 1;
select id, pg_typeof((select sum(bi) from b53_t t where t.x = o.a and t.y > o.b)), pg_typeof((select avg(fl) from b53_t t where t.x = o.a and t.y > o.b)) from b53_o o where id < 3 order by 1;
select sum((select sum(nu) from b53_t t where t.x = o.a and t.y > o.b)) from b53_o o where o.id in (1, 2, 3, 6, 9);
select sum(fl) from b53_t where x = 2;
select avg(fl) from b53_t where x = 6;
select sum(fl) over (order by id) from b53_t where x = 2;
select x, sum(fl), avg(fl) from b53_t where x in (1, 3, 4, 5) group by x order by 1;
select sum(fl) from b53_t where x in (4, 5);
select sum(re), avg(re) from b53_t;
select id, (select 1 / (t.y - t.y) from b53_t t where t.x = o.a limit 1) from b53_o o order by 1;
select (select 1 / (y - y) from b53_t where id = 1);
