select id, (select count(*) from b54_t t where t.x = o.a and t.n > o.n) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and t.n <= o.n) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and t.n <> o.n) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and t.nb >= o.n) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and o.n < t.n) from b54_o o order by 1;
select id, exists (select 1 from b54_t t where t.x = o.a and t.n > o.n) from b54_o o order by 1;
select id, (select max(y) from b54_t t where t.x = o.a and t.n >= o.n) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and t.n > o.b) from b54_o o order by 1;
select id, (select sum(re) from b54_t t where t.x = o.a and t.y > o.b) from b54_o o order by 1;
select id, (select avg(re) from b54_t t where t.x = o.a and t.y > o.b) from b54_o o order by 1;
select id, (select sum(re) from b54_t t where t.x = o.a and t.y >= o.b and t.y < o.b + 5) from b54_o o order by 1;
select id, pg_typeof((select sum(re) from b54_t t where t.x = o.a and t.y > o.b)), pg_typeof((select avg(re) from b54_t t where t.x = o.a and t.y > o.b)) from b54_o o where id < 3 order by 1;
select id, (select upper(t.s) from b54_t t where t.x = o.a order by t.y limit 1) from b54_o o order by 1;
select id, (select string_agg(lower(t.s), ',' order by t.y) from b54_t t where t.x = o.a) from b54_o o order by 1;
select id, array(select abs(t.y - 5) from b54_t t where t.x = o.a order by t.y) from b54_o o order by 1;
select id, (select round(t.n, 1) from b54_t t where t.x = o.a order by t.y limit 1) from b54_o o order by 1;
select id, (select max(length(t.s)) from b54_t t where t.x = o.a) from b54_o o order by 1;
select id, (select 8 / t.z from b54_t t where t.x = o.a and t.z > 0 order by t.y limit 1) from b54_o o order by 1;
select id, (select 12 / t.y from b54_t t where t.x = o.a order by t.y limit 1) from b54_o o order by 1;
select id, (select sqrt(t.y - 2) from b54_t t where t.x = o.a order by t.y desc limit 1) from b54_o o where o.a > 1 order by 1;
select id, (select (t.s || 'x')::text from b54_t t where t.x = o.a order by t.y limit 1) from b54_o o order by 1;
select id, exists (select 1 from generate_series(1, 3) g where g = o.a) from b54_o o order by 1;
select id, (select count(*) from generate_series(1, 10) g where g = o.a or g = o.b) from b54_o o order by 1;
select id, (select g.v from unnest(array[10, 20, 30]) with ordinality g(v, i) where g.i = o.a) from b54_o o order by 1;
select id, (select count(*) from b54_t t join generate_series(1, 6) g on g = t.y where t.x = o.a) from b54_o o order by 1;
select id, (select count(*) from b54_t t where t.x = o.a and t.s > o.s) from b54_o o order by 1;
select sum(re) from b54_t where x = 2;
select sum(re), avg(re) from b54_t where x in (1, 3, 5);
select x, sum(re) from b54_t where x <> 2 group by x order by 1;
