# ORDER BY of stored columns in a block's DECLARE CURSOR: sorted at the first
# fetch in bounded memory (batch 58); NULL placement, ties, OFFSET / LIMIT,
# the block's own writes, moves back past the window.
BEGIN
INSERT INTO b58_bo VALUES (1000, 99, 'mine', 0.5), (1001, NULL, 'mine2', 1.5)
DECLARE c1 SCROLL CURSOR FOR SELECT id, k FROM b58_bo ORDER BY k DESC NULLS LAST, id
FETCH 5 FROM c1
FETCH FORWARD 300 FROM c1
FETCH BACKWARD 3 FROM c1
FETCH ABSOLUTE 2 FROM c1
FETCH ABSOLUTE -1 FROM c1
MOVE ABSOLUTE 0 IN c1
FETCH 4 FROM c1
DECLARE c2 CURSOR FOR SELECT t, id FROM b58_bo WHERE id > 100 ORDER BY t, id DESC OFFSET 7 LIMIT 20
FETCH ALL FROM c2
DECLARE c3 CURSOR FOR SELECT id, f FROM b58_bo ORDER BY f DESC, id LIMIT 3
FETCH ALL FROM c3
DECLARE c4 CURSOR FOR SELECT id, k FROM b58_bo ORDER BY k NULLS FIRST, id
FETCH 10 FROM c4
UPDATE b58_bo SET k = -1 WHERE id = 1
FETCH 3 FROM c4
CLOSE c4
DECLARE c5 SCROLL CURSOR FOR SELECT id FROM b58_bo WHERE k = 3 ORDER BY t DESC, id
FETCH ALL FROM c5
FETCH BACKWARD 2 FROM c5
ROLLBACK
