# DISTINCT and friends de-duplicated through a hash on the same identity
# (batch 59): numerics by value, every NaN one value, -0 as 0, NULLs one
# value; the first row of each group printed.
SELECT DISTINCT n FROM b59_d WHERE id < 10 ORDER BY n
SELECT DISTINCT f FROM b59_d WHERE id < 10 ORDER BY f
SELECT DISTINCT t FROM b59_d WHERE id < 10 ORDER BY t
SELECT DISTINCT b, n FROM b59_d WHERE id < 10 ORDER BY b, n
SELECT DISTINCT a FROM b59_d WHERE id < 10 ORDER BY a
SELECT count(*) FROM (SELECT DISTINCT n, t FROM b59_d) s
SELECT count(*) FROM (SELECT DISTINCT f, b FROM b59_d) s
SELECT DISTINCT ON (n) n, id FROM b59_d WHERE id < 10 ORDER BY n, id DESC
SELECT DISTINCT ON (f) f, id FROM b59_d WHERE id < 10 ORDER BY f, id
SELECT count(DISTINCT n) FROM b59_d WHERE id < 10
SELECT count(DISTINCT f) FROM b59_d WHERE id < 10
SELECT array_agg(DISTINCT n) FROM b59_d WHERE id < 10
SELECT array_agg(DISTINCT f) FROM b59_d WHERE id < 10
SELECT array_agg(DISTINCT t) FROM b59_d WHERE id < 10
SELECT sum(DISTINCT n), avg(DISTINCT n) FROM b59_d WHERE id < 10
SELECT b, count(DISTINCT n) FROM b59_d GROUP BY b ORDER BY b
SELECT DISTINCT b, count(*) > 100 FROM b59_d GROUP BY b, n ORDER BY 1, 2
SELECT n FROM b59_d WHERE id < 10 UNION SELECT 1 ORDER BY 1
SELECT f FROM b59_d WHERE id < 10 UNION SELECT -0.0::float8 ORDER BY 1
SELECT n FROM b59_d WHERE id < 10 INTERSECT SELECT 1.000 ORDER BY 1
SELECT n FROM b59_d WHERE id < 10 INTERSECT ALL SELECT n FROM b59_d WHERE id < 4 ORDER BY 1
SELECT n FROM b59_d WHERE id < 10 EXCEPT SELECT 1 ORDER BY 1
SELECT n FROM b59_d WHERE id < 10 EXCEPT ALL SELECT 1 ORDER BY 1
SELECT f FROM b59_d WHERE id < 10 EXCEPT ALL SELECT 'NaN'::float8 ORDER BY 1
SELECT count(*) FROM (SELECT n FROM b59_d UNION SELECT n FROM b59_d) s
SELECT count(*) FROM (SELECT t FROM b59_d INTERSECT ALL SELECT t FROM b59_d WHERE id % 2 = 0) s
SELECT count(*) FROM (SELECT t, b FROM b59_d EXCEPT ALL SELECT t, b FROM b59_d WHERE id % 3 = 0) s
SELECT count(*) FROM (SELECT DISTINCT id % 1000, t FROM b59_d) s
SELECT DISTINCT lower(t) FROM b59_d WHERE id < 10 ORDER BY 1
SELECT DISTINCT t COLLATE "C" FROM b59_d WHERE id < 10 ORDER BY 1
SELECT count(DISTINCT n), count(DISTINCT f), count(DISTINCT t) FROM b59_d
SELECT n, count(*) FROM b59_d WHERE id < 10 GROUP BY n ORDER BY n
SELECT f, count(*) FROM b59_d WHERE id < 10 GROUP BY f ORDER BY f
SELECT count(*) FROM (SELECT n, t FROM b59_d GROUP BY n, t) s
SELECT count(*) FROM (SELECT DISTINCT ARRAY[n] FROM b59_d WHERE id < 10) s
SELECT count(*) FROM (SELECT DISTINCT ARRAY[f] FROM b59_d WHERE id < 10) s
SELECT n FROM b59_d WHERE id < 10 UNION SELECT 1.5::float8 ORDER BY 1
SELECT id % 3 FROM b59_d WHERE id < 10 INTERSECT SELECT 2.0 ORDER BY 1
