# DISTINCT, DISTINCT ON and ORDER BY over an expression, streamed in
# bounded memory (batch 59): outside a block (a statement with no WHERE),
# through a block's DECLARE CURSOR, with OFFSET / LIMIT and the block's own
# writes.
SELECT id, k FROM b59_s ORDER BY k * -1 NULLS FIRST, id LIMIT 20
SELECT id, t FROM b59_s ORDER BY upper(t) DESC, id OFFSET 590
SELECT id FROM b59_s ORDER BY id % 17, f DESC LIMIT 12
SELECT DISTINCT k FROM b59_s ORDER BY k
SELECT DISTINCT k, t FROM b59_s ORDER BY t DESC, k LIMIT 15
SELECT DISTINCT n FROM b59_s ORDER BY n
SELECT DISTINCT k FROM b59_s ORDER BY k DESC NULLS LAST OFFSET 2 LIMIT 5
SELECT count(*) FROM (SELECT DISTINCT k, t FROM b59_s) s
SELECT DISTINCT ON (k) k, id FROM b59_s ORDER BY k, id DESC
SELECT DISTINCT ON (t) t, f FROM b59_s ORDER BY t, f
SELECT DISTINCT ON (k, t) k, t, id FROM b59_s ORDER BY k, t, id LIMIT 10
SELECT id FROM b59_s ORDER BY 1 / (id - 300), id LIMIT 3
BEGIN
INSERT INTO b59_s VALUES (1000, 50, 'mine', 0.5, 9.5)
DECLARE c1 SCROLL CURSOR FOR SELECT id, k FROM b59_s ORDER BY coalesce(k, 100) DESC, id
FETCH 5 FROM c1
FETCH FORWARD 300 FROM c1
FETCH BACKWARD 3 FROM c1
FETCH ABSOLUTE 2 FROM c1
FETCH ABSOLUTE -1 FROM c1
DECLARE c2 CURSOR FOR SELECT DISTINCT k, t FROM b59_s ORDER BY t, k OFFSET 7 LIMIT 20
FETCH ALL FROM c2
DECLARE c3 SCROLL CURSOR FOR SELECT DISTINCT n FROM b59_s ORDER BY n DESC
FETCH 3 FROM c3
FETCH PRIOR FROM c3
FETCH ALL FROM c3
DECLARE c4 CURSOR FOR SELECT DISTINCT ON (t) t, id FROM b59_s ORDER BY t, id DESC
FETCH 4 FROM c4
UPDATE b59_s SET t = 'zz' WHERE id = 1
FETCH ALL FROM c4
DECLARE c5 CURSOR FOR SELECT id, t FROM b59_s ORDER BY length(t) DESC, t, id LIMIT 8
FETCH ALL FROM c5
ROLLBACK
