# reference-version: 15
# Batch 64: an EXISTS subquery's select list is never evaluated (simplify_EXISTS_query).
SELECT exists(SELECT 1/0)
SELECT exists(SELECT 1/0 FROM b64_e)
SELECT exists(SELECT 1/0 FROM b64_e0)
SELECT exists(SELECT a/b FROM b64_e)
SELECT not exists(SELECT a/b FROM b64_e WHERE a > 1)
SELECT count(*) FROM b64_e o WHERE exists(SELECT 1/0 FROM b64_e i WHERE i.a = o.a)
SELECT count(*) FROM b64_e o WHERE exists(SELECT i.a/i.b FROM b64_e i WHERE i.a > o.a)
SELECT exists(SELECT DISTINCT a/b FROM b64_e ORDER BY a/b)
SELECT exists(SELECT a/b FROM b64_e LIMIT 1)
SELECT exists(SELECT max(a)/0 FROM b64_e)
SELECT exists(SELECT max(a) FROM b64_e0)
SELECT exists(SELECT generate_series(1, 0))
SELECT exists(SELECT a FROM b64_e GROUP BY a HAVING a > 5)
SELECT exists(SELECT 1/0 UNION SELECT 2)
SELECT exists(SELECT (SELECT 1/0))
# float math errors (float.c)
SELECT sqrt(-1)
SELECT sqrt(-1::float8)
SELECT |/ -4
SELECT ln(-1)
SELECT ln(0)
SELECT log(-1)
SELECT log(0::float8)
SELECT log10(-2)
SELECT ln(2::float8), log(100::float8), sqrt(2::float8)
SELECT power(-8::float8, 0.5::float8)
SELECT power(0::float8, -1::float8)
SELECT power(-8::float8, 3::float8), power(2::float8, -2::float8)
SELECT power('NaN'::float8, 0::float8), power('NaN'::float8, 1::float8), power(1::float8, 'NaN'::float8)
SELECT power(2::float8, 'Infinity'::float8), power(0.5::float8, 'Infinity'::float8), power(2::float8, '-Infinity'::float8)
SELECT power('-Infinity'::float8, 3::float8), power('-Infinity'::float8, -3::float8), power('-Infinity'::float8, 2::float8)
SELECT power(10::float8, 400::float8)
SELECT power(10::float8, -400::float8)
SELECT exp(1000::float8)
SELECT exp(-1000::float8)
SELECT exp(1::float8), exp('-Infinity'::float8), exp('Infinity'::float8)
SELECT 2.0::float8 ^ 3.0::float8, (-2)::float8 ^ 0.5::float8
SELECT exists(SELECT a/b FROM b64_e LIMIT 0)
SELECT exists(SELECT a/b FROM b64_e LIMIT ALL)
