# reference-version: 15
# Batch 64: a plain SELECT DISTINCT's ORDER BY must name the select list (42P10 otherwise).
SELECT DISTINCT v FROM b64_do ORDER BY v + 1
SELECT DISTINCT v FROM b64_do ORDER BY -v
SELECT DISTINCT v FROM b64_do ORDER BY v::text
SELECT DISTINCT v FROM b64_do ORDER BY 1::text
SELECT DISTINCT v FROM b64_do ORDER BY w
SELECT DISTINCT v + 1 FROM b64_do ORDER BY v
SELECT DISTINCT v + 1 AS x FROM b64_do ORDER BY v + 1
SELECT DISTINCT v + 1 AS x FROM b64_do ORDER BY x DESC
SELECT DISTINCT v FROM b64_do ORDER BY 1 DESC
SELECT DISTINCT v FROM b64_do ORDER BY v DESC
SELECT DISTINCT b64_do.v FROM b64_do ORDER BY v
SELECT DISTINCT v FROM b64_do ORDER BY b64_do.v DESC
SELECT DISTINCT d.v FROM b64_do d ORDER BY d.v
SELECT DISTINCT * FROM b64_do ORDER BY v, w
SELECT DISTINCT * FROM b64_do ORDER BY v + 1
SELECT DISTINCT v, upper(t) FROM b64_do ORDER BY upper(t) DESC, v
SELECT DISTINCT v, upper(t) FROM b64_do ORDER BY lower(t)
SELECT DISTINCT v, t FROM b64_do ORDER BY t || 'x'
SELECT DISTINCT count(*) FROM b64_do ORDER BY count(*)
SELECT DISTINCT v, count(*) FROM b64_do GROUP BY v ORDER BY count(*) DESC, v
SELECT DISTINCT v, count(*) FROM b64_do GROUP BY v ORDER BY sum(w)
SELECT DISTINCT v FROM b64_do GROUP BY v, w ORDER BY w
SELECT x FROM (SELECT DISTINCT v AS x FROM b64_do ORDER BY v * 2) s
SELECT DISTINCT ON (v) v, w FROM b64_do ORDER BY v, w DESC
SELECT v FROM b64_do ORDER BY v + 1, w
SELECT DISTINCT v FROM b64_do WHERE v > 1 ORDER BY (v)
SELECT DISTINCT (v) FROM b64_do ORDER BY v
SELECT DISTINCT v FROM b64_do ORDER BY v COLLATE "C"
