# reference-version: 15
# Batch 65: a COLLATE on a type that takes none is a planning error (42804), even over no rows.
SELECT v FROM b65_r0 ORDER BY v COLLATE "C"
SELECT v FROM b65_r ORDER BY v COLLATE "C"
SELECT v FROM b65_r0 ORDER BY b65_r0.v COLLATE "C"
SELECT v COLLATE "C" FROM b65_r0
SELECT t FROM b65_r0 ORDER BY t COLLATE "C"
SELECT t FROM b65_r ORDER BY t COLLATE "C" DESC
SELECT d FROM b65_r ORDER BY d COLLATE "C"
SELECT j FROM b65_r ORDER BY j COLLATE "C"
SELECT n FROM b65_r ORDER BY n COLLATE "C"
SELECT x.v FROM b65_r0 x ORDER BY x.v COLLATE "POSIX"
SELECT v FROM b65_r0 ORDER BY v COLLATE "nope"
SELECT DISTINCT v FROM b65_r0 ORDER BY v COLLATE "C"
# a COLLATE makes an ORDER BY item another expression: 42P10 under a plain DISTINCT
SELECT DISTINCT t FROM b65_r ORDER BY t COLLATE "C"
SELECT DISTINCT t FROM b65_r0 ORDER BY t COLLATE "C"
SELECT DISTINCT t COLLATE "C" FROM b65_r ORDER BY t COLLATE "C"
SELECT DISTINCT t COLLATE "C" AS u FROM b65_r ORDER BY u
SELECT DISTINCT t, v FROM b65_r ORDER BY t COLLATE "C", v
SELECT DISTINCT ON (t) t FROM b65_r ORDER BY t COLLATE "C"
# rows OFFSET skips are still projected
SELECT exists(SELECT a/b FROM b65_r LIMIT 1 OFFSET 5)
SELECT exists(SELECT a/b FROM b65_r OFFSET 5)
SELECT exists(SELECT a/b FROM b65_r OFFSET 1)
SELECT exists(SELECT a FROM b65_r OFFSET 5)
SELECT exists(SELECT a FROM b65_r OFFSET 1)
SELECT exists(SELECT a/b FROM b65_r0 OFFSET 5)
SELECT exists(SELECT a/b FROM b65_r WHERE a > 5 OFFSET 1)
SELECT a/b FROM b65_r LIMIT 1 OFFSET 5
SELECT a/b FROM b65_r OFFSET 2
SELECT a FROM b65_r ORDER BY a OFFSET 5
SELECT not exists(SELECT a/b FROM b65_r LIMIT 1 OFFSET 2)
SELECT a/b FROM b65_r ORDER BY v DESC OFFSET 2
SELECT a/b, v FROM b65_r ORDER BY v OFFSET 1 LIMIT 1
SELECT t || 'x' FROM b65_r ORDER BY v OFFSET 1
SELECT nextval('b65_seq') FROM b65_r OFFSET 1
SELECT currval('b65_seq')
# DISTINCT ON's leading ORDER BY items must be its expressions
SELECT DISTINCT ON (t) t FROM b65_r ORDER BY v
SELECT DISTINCT ON (t) t, v FROM b65_r ORDER BY t, v
SELECT DISTINCT ON (t, v) t, v FROM b65_r ORDER BY v, t
SELECT DISTINCT ON (1) t FROM b65_r ORDER BY t
SELECT DISTINCT ON (t) t AS u FROM b65_r ORDER BY u
SELECT DISTINCT ON (t) t FROM b65_r ORDER BY 1
SELECT DISTINCT ON (b65_r.t) t FROM b65_r ORDER BY t
SELECT DISTINCT ON (t) t FROM b65_r ORDER BY t || 'x'
SELECT DISTINCT ON (t, v) t, v FROM b65_r ORDER BY t, a
SELECT DISTINCT ON (upper(t)) t FROM b65_r ORDER BY upper(t), v
SELECT DISTINCT ON (upper(t)) t FROM b65_r ORDER BY lower(t)
SELECT DISTINCT ON (t) t FROM b65_r0 ORDER BY v
