DROP PUBLICATION IF EXISTS co_pb
DROP PUBLICATION IF EXISTS co_pb2
DROP TABLE IF EXISTS co_t CASCADE
DROP TABLE IF EXISTS co_u CASCADE
CREATE TABLE co_t (a int, b int, c text)
CREATE TABLE co_u (x int)
