DROP VIEW IF EXISTS cm_v
DROP TABLE IF EXISTS cm_t
DROP SEQUENCE IF EXISTS cm_s
CREATE TABLE cm_t (id int PRIMARY KEY, a int CONSTRAINT cm_chk CHECK (a > 0), b text UNIQUE)
CREATE INDEX cm_i ON cm_t (a)
CREATE SEQUENCE cm_s
CREATE VIEW cm_v AS SELECT 1 AS x
