CREATE CONSTRAINT TRIGGER ct_imm AFTER INSERT ON ct_t FOR EACH ROW EXECUTE FUNCTION ct_chk()
CREATE CONSTRAINT TRIGGER ct_def AFTER UPDATE ON ct_t DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ct_chk()
INSERT INTO ct_t VALUES (1, 1)
INSERT INTO ct_t VALUES (2, -1)
SELECT msg FROM ct_log ORDER BY msg
BEGIN
UPDATE ct_t SET n = -5 WHERE id = 1
SELECT count(*) FROM ct_log
COMMIT
SELECT n FROM ct_t WHERE id = 1
BEGIN
UPDATE ct_t SET n = 7 WHERE id = 1
SELECT count(*) FROM ct_log
COMMIT
SELECT count(*) FROM ct_log
BEGIN
UPDATE ct_t SET n = 8 WHERE id = 1
SET CONSTRAINTS ct_def IMMEDIATE
SELECT count(*) FROM ct_log
COMMIT
SELECT tgname, tgdeferrable, tginitdeferred, tgconstraint <> 0 FROM pg_trigger WHERE tgrelid = 'ct_t'::regclass ORDER BY 1
SET CONSTRAINTS ALL DEFERRED
BEGIN
SET CONSTRAINTS nosuch DEFERRED
ROLLBACK
BEGIN
SET CONSTRAINTS ct_imm DEFERRED
ROLLBACK
BEGIN
SET CONSTRAINTS ALL DEFERRED
INSERT INTO ct_c VALUES (1, 10)
INSERT INTO ct_p VALUES (10)
COMMIT
SELECT * FROM ct_c
BEGIN
SET CONSTRAINTS ALL DEFERRED
INSERT INTO ct_c VALUES (2, 20)
SET CONSTRAINTS ALL IMMEDIATE
ROLLBACK
BEGIN
INSERT INTO ct_c VALUES (3, 30)
ROLLBACK
