DROP TABLE IF EXISTS ct_t
DROP TABLE IF EXISTS ct_log
DROP TABLE IF EXISTS ct_c
DROP TABLE IF EXISTS ct_p
CREATE TABLE ct_t (id int PRIMARY KEY, n int)
CREATE TABLE ct_log (msg text)
CREATE TABLE ct_p (id int PRIMARY KEY)
CREATE TABLE ct_c (id int PRIMARY KEY, p int REFERENCES ct_p DEFERRABLE INITIALLY IMMEDIATE)
CREATE OR REPLACE FUNCTION ct_chk() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO ct_log VALUES (TG_NAME || ' ' || NEW.id); IF NEW.n < 0 THEN RAISE EXCEPTION 'negative n for %', NEW.id; END IF; RETURN NULL; END $$
