DROP TYPE IF EXISTS ct_b CASCADE
DROP TYPE IF EXISTS ct_c CASCADE
DROP TYPE IF EXISTS pt_s
DROP DOMAIN IF EXISTS pt_d
DROP TYPE IF EXISTS pt_e, pt_c, pt_r
DROP TYPE IF EXISTS cto_0 CASCADE
DROP TYPE IF EXISTS cto_1 CASCADE
DROP TYPE IF EXISTS cto_2 CASCADE
DROP TYPE IF EXISTS cto_3 CASCADE
DROP TYPE IF EXISTS cto_4 CASCADE
DROP TYPE IF EXISTS cto_5 CASCADE
DROP TYPE IF EXISTS cto_6 CASCADE
DROP TYPE IF EXISTS cto_7 CASCADE
DROP TYPE IF EXISTS cto_8 CASCADE
DROP TYPE IF EXISTS cto_9 CASCADE
DROP TYPE IF EXISTS cto_10 CASCADE
DROP TYPE IF EXISTS cto_11 CASCADE
DROP TYPE IF EXISTS cto_12 CASCADE
DROP TYPE IF EXISTS cto_13 CASCADE
DROP TYPE IF EXISTS cto_14 CASCADE
DROP TYPE IF EXISTS cto_15 CASCADE
DROP TYPE IF EXISTS cto_16 CASCADE
DROP TYPE IF EXISTS cto_17 CASCADE
