# --- constraint enforcement
INSERT INTO p10 VALUES (3, 1, 'a', 1)
INSERT INTO p10 VALUES (3, NULL, 'c', 1)
INSERT INTO p10 VALUES (3, 1, 'c', -1)
INSERT INTO p10 VALUES (1, 1, 'z', 1)
INSERT INTO ch10 VALUES (12, 99, 1)
DELETE FROM p10 WHERE id = 1
UPDATE p10 SET c = -5 WHERE id = 1
UPDATE p10 SET s = 'b' WHERE id = 1
UPDATE ch10 SET pid = 77 WHERE id = 10
# --- ALTER
ALTER TABLE p10 ADD COLUMN extra text DEFAULT 'dflt'
SELECT id, extra FROM p10 ORDER BY id
ALTER TABLE p10 ALTER COLUMN extra SET DEFAULT 'new'
ALTER TABLE p10 ALTER COLUMN extra DROP DEFAULT
ALTER TABLE p10 ADD CONSTRAINT chk_n CHECK (n >= 0)
INSERT INTO p10 (id, n, s, c) VALUES (4, -1, 'd', 1)
ALTER TABLE p10 DROP CONSTRAINT chk_n
ALTER TABLE p10 RENAME COLUMN extra TO extra2
SELECT extra2 FROM p10 WHERE id = 1
ALTER TABLE p10 ALTER COLUMN n TYPE bigint
ALTER TABLE p10 ALTER COLUMN n SET NOT NULL
ALTER TABLE p10 ALTER COLUMN n DROP NOT NULL
ALTER TABLE p10 DROP COLUMN extra2
SELECT count(*) FROM p10
ALTER TABLE p10 RENAME TO p10b
SELECT count(*) FROM p10b
ALTER TABLE p10b RENAME TO p10
# --- indexes / views
CREATE INDEX idx10 ON p10 (n)
CREATE UNIQUE INDEX uidx10 ON p10 (s)
DROP INDEX idx10
CREATE VIEW v10 AS SELECT id, n FROM p10 WHERE n > 0
SELECT count(*) FROM v10
CREATE OR REPLACE VIEW v10 AS SELECT id FROM p10
DROP VIEW v10
# --- error surface
CREATE TABLE p10 (id int)
DROP TABLE nope10
DROP TABLE IF EXISTS nope10
ALTER TABLE nope10 ADD COLUMN x int
ALTER TABLE p10 ADD COLUMN id int
ALTER TABLE p10 DROP COLUMN nope
SELECT * FROM nope10
CREATE TABLE bad10 (id int, id int)
