select count(distinct k) from (values ('a' collate dc14_ci), ('A')) v(k);
select k from (values ('a' collate dc14_ci), ('A'), ('b')) v(k) where k = 'A' order by 1;
select k, count(*) from (values ('a' collate dc14_ci), ('A'), ('b')) v(k) group by k order by 1;
select k, count(*) from (values ('A' collate dc14_ci), ('a'), ('b')) v(k) group by k order by 1;
select count(distinct k) from (select 'a' collate dc14_ci as k union all select 'A') s;
select count(distinct x) from (select 'a' collate dc14_ci union all select 'A') s(x);
with c(k) as (values ('x' collate dc14_ci), ('X')) select count(distinct k) from c;
with c as (select 'x' collate dc14_ci as k union all select 'X') select k, count(*) from c group by k order by 1;
select k from (values ('b' collate "C"), ('a'), ('B')) v(k) order by k;
select k, count(*) from dc14_t group by k order by 1;
select k, count(*) from dc14_t group by k order by 1 desc;
select distinct k from dc14_t order by 1;
select count(distinct k) from dc14_t;
select (array_agg(k))[1], count(*) from (values ('a'), ('A'), ('b')) v(k) group by lower(k) order by 1;
select (array_agg(n order by n desc))[2] from (values (1), (3), (2)) v(n);
select lower(k), (array_agg(k order by k))[1:2] from dc14_t group by lower(k) order by 1;
select greatest(max(n), 10) from (values (1), (3), (2)) v(n);
select max(n) is null from (values (1), (3), (2)) v(n);
select (array_agg(n order by n))[2:3] from (values (1), (3), (2)) v(n);
