SELECT id FROM dd WHERE n IS NOT DISTINCT FROM 10 ORDER BY id
SELECT id FROM dd WHERE n IS DISTINCT FROM 10 ORDER BY id
SELECT id FROM dd WHERE n IS NOT DISTINCT FROM NULL ORDER BY id
SELECT id FROM dd WHERE n IS DISTINCT FROM NULL ORDER BY id
SELECT id FROM dd WHERE s IS DISTINCT FROM 'a' ORDER BY id
SELECT id, n IS DISTINCT FROM 10 FROM dd ORDER BY id
SELECT NULL IS DISTINCT FROM NULL, 1 IS DISTINCT FROM NULL, 1 IS NOT DISTINCT FROM 1
SELECT a.id, b.id FROM dd a JOIN dd b ON a.n IS NOT DISTINCT FROM b.n ORDER BY 1
DELETE FROM dd WHERE n IS NOT DISTINCT FROM NULL RETURNING id
