# --- INSERT ... RETURNING
INSERT INTO d9 VALUES (10, 1, 'a') RETURNING id
INSERT INTO d9 VALUES (11, 2, 'b') RETURNING *
INSERT INTO d9 VALUES (12, 3, 'c') RETURNING id, n * 2 AS dbl
INSERT INTO d9 VALUES (13, 4, 'd') RETURNING id AS k, upper(s)
INSERT INTO d9 (id) VALUES (14) RETURNING id, n, s
INSERT INTO d9 VALUES (15, 5, 'e'), (16, 6, 'f') RETURNING id
INSERT INTO d9 SELECT 17, 7, 'g' RETURNING id
INSERT INTO d9 VALUES (18, 8, 'h') RETURNING id, (SELECT count(*) FROM d9)
# --- UPDATE / DELETE RETURNING
UPDATE d9 SET n = n + 100 WHERE id = 10 RETURNING id, n
UPDATE d9 SET n = n + 1 WHERE id = 11 RETURNING *
UPDATE d9 SET s = 'zz' WHERE id = 999 RETURNING id
DELETE FROM d9 WHERE id = 16 RETURNING id, s
DELETE FROM d9 WHERE id = 998 RETURNING id
UPDATE d9 SET n = 0 WHERE id IN (12, 13) RETURNING id ORDER BY id
# --- ON CONFLICT
INSERT INTO d9 VALUES (10, 999, 'dup') ON CONFLICT (id) DO NOTHING RETURNING id
INSERT INTO d9 VALUES (10, 999, 'dup') ON CONFLICT (id) DO UPDATE SET n = EXCLUDED.n RETURNING id, n
INSERT INTO d9 VALUES (20, 1, 'x') ON CONFLICT (id) DO UPDATE SET n = EXCLUDED.n RETURNING id, n
INSERT INTO d9 VALUES (20, 2, 'y') ON CONFLICT (id) DO UPDATE SET n = d9.n + EXCLUDED.n RETURNING id, n
INSERT INTO d9 VALUES (20, 3, 'z') ON CONFLICT (id) DO UPDATE SET n = 5 WHERE d9.n > 100 RETURNING id, n
INSERT INTO d9 VALUES (21, 1, 'q') ON CONFLICT DO NOTHING RETURNING id
# --- UPDATE FROM / DELETE USING
UPDATE d9 SET n = o.n FROM (SELECT 10 AS id, 42 AS n) o WHERE d9.id = o.id RETURNING d9.id, d9.n
DELETE FROM d9 USING (SELECT 21 AS id) o WHERE d9.id = o.id RETURNING d9.id
# --- multi-row / expression updates
UPDATE d9 SET (n, s) = (7, 'tup') WHERE id = 11 RETURNING id, n, s
UPDATE d9 SET n = DEFAULT WHERE id = 11 RETURNING id, n
UPDATE d9 SET n = n WHERE false RETURNING id
SELECT id, n, s FROM d9 ORDER BY id
