DROP TABLE IF EXISTS dc_p CASCADE
DROP TABLE IF EXISTS dc_c CASCADE
DROP TABLE IF EXISTS dc_c2 CASCADE
DROP TABLE IF EXISTS dc_s CASCADE
CREATE TABLE dc_p (id int PRIMARY KEY)
CREATE TABLE dc_c (x int REFERENCES dc_p)
CREATE TABLE dc_c2 (y int CONSTRAINT yfk REFERENCES dc_p)
CREATE TABLE dc_s (id int PRIMARY KEY, parent int REFERENCES dc_s)
INSERT INTO dc_p VALUES (1)
INSERT INTO dc_c VALUES (1)
CREATE VIEW dc_v AS SELECT * FROM dc_p
CREATE VIEW dc_vv AS SELECT * FROM dc_v
