DROP EVENT TRIGGER IF EXISTS etc_rw_t
DROP EVENT TRIGGER IF EXISTS etc_end_t
DROP EVENT TRIGGER IF EXISTS etc_drop_t
DROP SCHEMA IF EXISTS etc_s
DROP TABLE IF EXISTS etc_t
DROP TABLE IF EXISTS etc_log
DROP VIEW IF EXISTS etc_v2
DROP VIEW IF EXISTS etc_v
DROP FUNCTION IF EXISTS etc_f2()
DROP FUNCTION IF EXISTS etc_f()
DROP FUNCTION IF EXISTS etc_rw()
DROP FUNCTION IF EXISTS etc_end()
DROP FUNCTION IF EXISTS etc_drop()
DROP EVENT TRIGGER IF EXISTS etn_t
DROP TABLE IF EXISTS etn_x
DROP TABLE IF EXISTS etn_y
DROP FUNCTION IF EXISTS etn_mk()
DROP FUNCTION IF EXISTS etn_f()
DROP TABLE IF EXISTS etn_log
