EXPLAIN (COSTS OFF) SELECT * FROM exq
EXPLAIN (COSTS OFF) SELECT * FROM exq ORDER BY g
EXPLAIN (COSTS OFF) SELECT * FROM exq ORDER BY g LIMIT 1
EXPLAIN (COSTS OFF) SELECT g, count(*) FROM exq GROUP BY g
EXPLAIN (COSTS OFF) SELECT count(*) FROM exq
EXPLAIN (COSTS OFF) INSERT INTO exq VALUES (3, 3, 'c')
EXPLAIN (COSTS OFF) SELECT 1
EXPLAIN (FORMAT YAML, COSTS OFF) SELECT 1
EXPLAIN (NOSUCH) SELECT 1
EXPLAIN SELECT * FROM nosuch
EXPLAIN (FORMAT XML, COSTS OFF) SELECT 1
EXPLAIN (FORMAT JSON, COSTS OFF) SELECT 1
