DROP TABLE IF EXISTS fkc
DROP TABLE IF EXISTS fkd
DROP TABLE IF EXISTS fke
DROP TABLE IF EXISTS fkf
DROP TABLE IF EXISTS fkg
DROP TABLE IF EXISTS fkh
DROP TABLE IF EXISTS fki
DROP TABLE IF EXISTS fkc
DROP TABLE IF EXISTS fkp
DROP TABLE IF EXISTS fku
CREATE TABLE fkp (a int, b text, v int, PRIMARY KEY (a, b))
CREATE TABLE fku (id int PRIMARY KEY, x int, y int, UNIQUE (x, y))
INSERT INTO fkp VALUES (1, 'x', 10), (2, 'y', 20)
INSERT INTO fku VALUES (1, 1, 1)
