# No ::text anywhere — that cast is itself broken and masked everything else.
SELECT to_tsvector('english', 'The quick brown fox')
SELECT to_tsvector('simple', 'The quick brown fox')
SELECT to_tsquery('english', 'quick & brown')
SELECT plainto_tsquery('english', 'quick brown')
SELECT phraseto_tsquery('english', 'quick brown')
SELECT websearch_to_tsquery('english', 'quick or brown')
SELECT to_tsvector('english','The quick brown fox') @@ to_tsquery('english','quick')
SELECT to_tsvector('english','The quick brown fox') @@ to_tsquery('english','slow')
SELECT 'a fat cat'::tsvector
SELECT 'fat & cat'::tsquery
SELECT setweight(to_tsvector('english','quick'), 'A')
SELECT strip(to_tsvector('english','quick brown'))
SELECT numnode(to_tsquery('english','quick & brown'))
SELECT querytree(to_tsquery('english','quick & brown'))
SELECT to_tsvector('english','running runs ran')
SELECT tsvector_to_array(to_tsvector('english','quick brown'))
SELECT to_tsvector('english','quick') || to_tsvector('english','brown')
SELECT to_tsquery('english','quick') && to_tsquery('english','brown')
SELECT to_tsquery('english','quick') || to_tsquery('english','brown')
SELECT !!to_tsquery('english','quick')
SELECT to_tsvector('english','the quick brown fox') @@ 'quick'::tsquery
SELECT ts_headline('english','the quick brown fox', to_tsquery('english','quick'))
SELECT to_tsvector('english','cats and dogs')
SELECT to_tsvector('english','a fat cat sat on a mat')
SELECT id FROM ts1 WHERE to_tsvector('english', title) @@ to_tsquery('english','quick') ORDER BY id
SELECT id FROM ts1 WHERE to_tsvector('english', body) @@ plainto_tsquery('english','lazy dog') ORDER BY id
SELECT to_tsvector('english','quick brown') @@ to_tsquery('english','quick <-> brown')
SELECT to_tsvector('english','quick brown') @@ to_tsquery('english','brown <-> quick')
SELECT to_tsvector('english','quick brown') @@ to_tsquery('english','qui:*')
SELECT strip(to_tsvector('simple','quick brown quick'))
SELECT numnode(to_tsquery('simple','quick & brown'))
SELECT numnode(to_tsquery('simple','quick'))
SELECT numnode(to_tsquery('simple','!quick'))
SELECT numnode(to_tsquery('simple','quick & brown | fox'))
SELECT querytree(to_tsquery('simple','quick & brown'))
SELECT querytree(to_tsquery('simple','!quick'))
SELECT tsvector_to_array(to_tsvector('simple','quick brown'))
SELECT array_to_tsvector(ARRAY['b','a'])
SELECT length(to_tsvector('simple','quick brown quick'))
SELECT tsvector_concat(to_tsvector('simple','quick brown'), to_tsvector('simple','lazy fox'))
SELECT tsquery_and(to_tsquery('simple','quick'), to_tsquery('simple','brown'))
SELECT tsquery_or(to_tsquery('simple','quick'), to_tsquery('simple','brown'))
SELECT tsquery_not(to_tsquery('simple','quick'))
SELECT to_tsvector('english','running runs ran')
SELECT to_tsvector('english','cats and dogs')
SELECT to_tsvector('simple','the running cats')
SELECT to_tsvector('english','the running cats')
SELECT to_tsvector('english','Running RUNS')
SELECT to_tsquery('english','running')
SELECT to_tsquery('english','running:*')
SELECT to_tsquery('simple','running')
SELECT plainto_tsquery('english','running cats')
SELECT phraseto_tsquery('english','running cats')
SELECT websearch_to_tsquery('english','running cats')
SELECT to_tsquery('english','runs & cats')
SELECT to_tsquery('english','the')
SELECT plainto_tsquery('english','the and of')
SELECT to_tsvector('english','the quick brown fox') @@ to_tsquery('english','quick')
SELECT id FROM ts1 WHERE to_tsvector('english', title) @@ to_tsquery('english','quick') ORDER BY id
SELECT id FROM ts1 WHERE to_tsvector('english', body) @@ plainto_tsquery('english','lazy dog') ORDER BY id
SELECT id FROM ts1 WHERE to_tsvector('english', body) @@ to_tsquery('english','run') ORDER BY id
SELECT to_tsvector('english','generalization oscillators university')
SELECT to_tsvector('english','feudalism decisiveness hopefulness')
SELECT to_tsquery('english','the & quick')
SELECT to_tsquery('english','quick & the')
SELECT to_tsquery('simple','the')
SELECT to_tsquery('english','!the')
SELECT to_tsquery('english','the <-> quick')
