# reference-version: 15
SELECT to_tsvector('french', 'Les chats mangeaient des souris dans la maison abandonnée')
SELECT to_tsquery('french', 'chat')
SELECT to_tsvector('german', 'Die Katzen fraßen Mäuse in den verlassenen Häusern')
SELECT to_tsvector('spanish', 'Los gatos comían ratones en las casas abandonadas')
SELECT to_tsvector('italian', 'I gatti mangiavano topi nelle case abbandonate')
SELECT to_tsvector('portuguese', 'Os gatos comiam ratos nas casas abandonadas')
SELECT to_tsvector('dutch', 'De katten aten muizen in de verlaten huizen')
SELECT to_tsvector('swedish', 'Katterna åt möss i de övergivna husen')
SELECT to_tsvector('danish', 'Kattene spiste mus i de forladte huse')
SELECT to_tsvector('norwegian', 'Kattene spiste mus i de forlatte husene')
SELECT to_tsvector('finnish', 'Kissat söivät hiiriä hylätyissä taloissa')
SELECT to_tsvector('hungarian', 'A macskák egereket ettek az elhagyott házakban')
SELECT to_tsvector('russian', 'Кошки ели мышей в заброшенных домах running')
SELECT to_tsvector('turkish', 'Kediler terk edilmiş evlerde fareleri yediler')
SELECT to_tsvector('romanian', 'Pisicile mâncau șoareci în casele abandonate')
SELECT to_tsvector('greek', 'οι γάτες έτρωγαν ποντίκια')
SELECT to_tsvector('arabic', 'القطط أكلت الفئران')
SELECT to_tsvector('french', 'nationalisation internationales généralement heureusement')
SELECT to_tsvector('german', 'Aufeinanderfolgende Entwicklungen wurden beschleunigt')
SELECT to_tsvector('english', 'The cats were running quickly')
SELECT to_tsvector('french', 'Le 42 rue-de-la-Paix abc123')
SELECT to_tsvector('french', 'le') @@ to_tsquery('french', 'le')
SELECT plainto_tsquery('spanish', 'los gatos comían')
SELECT websearch_to_tsquery('german', 'katzen -hunde "alte häuser"')
SELECT ts_rank(to_tsvector('french', 'les chats et les chiens'), to_tsquery('french', 'chat'))
SELECT to_tsvector('pg_catalog.french', 'chats')
SELECT to_tsvector('basque', 'etxea')
SELECT to_tsvector('klingon', 'x')
SELECT 'french'::regconfig
SELECT to_tsvector('catalan', 'Els gats menjaven ratolins a les cases abandonades')
SELECT to_tsvector('indonesian', 'Kucing-kucing memakan tikus di rumah-rumah yang ditinggalkan')
SELECT to_tsvector('irish', 'D''ith na cait lucha sna tithe tréigthe')
SELECT to_tsvector('lithuanian', 'Katės valgė peles apleistuose namuose')
SELECT to_tsvector('serbian', 'Мачке су јеле мишеве у напуштеним кућама')
SELECT to_tsvector('armenian', 'Կատուները ուտում էին մկներ')
SELECT to_tsvector('hindi', 'बिल्लियाँ चूहे खा रही थीं')
SELECT to_tsvector('nepali', 'बिरालाहरूले मुसा खाए')
SELECT to_tsvector('yiddish', 'די קעצלעך האָבן געגעסן מײַז')
SELECT to_tsvector('simple', '«bonjour» a—b ½x €5 ①')
SELECT to_tsvector('english', 'naïve café — «quoted» x²')
