GRANT SELECT, INSERT ON gr_t TO gr_r
GRANT ALL ON gr_t TO PUBLIC
GRANT ALL PRIVILEGES ON TABLE gr_t TO gr_r WITH GRANT OPTION
GRANT SELECT ON gr_t TO nosuch
GRANT SELECT ON nosuchtab TO gr_r
GRANT USAGE ON gr_t TO gr_r
REVOKE INSERT ON gr_t FROM gr_r
REVOKE ALL ON gr_t FROM PUBLIC
GRANT USAGE ON SCHEMA public TO gr_r
GRANT SELECT ON ALL TABLES IN SCHEMA public TO gr_r
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO gr_r
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO gr_r
GRANT gr_r TO CURRENT_USER
REVOKE gr_r FROM CURRENT_USER
GRANT nosuch TO gr_r
GRANT SELECT ON gr_t TO CURRENT_USER
SELECT count(*) FROM gr_t
