SELECT rank(20) WITHIN GROUP (ORDER BY v) FROM hs
SELECT dense_rank(20) WITHIN GROUP (ORDER BY v) FROM hs
SELECT percent_rank(20) WITHIN GROUP (ORDER BY v) FROM hs
SELECT cume_dist(20) WITHIN GROUP (ORDER BY v) FROM hs
SELECT rank(5) WITHIN GROUP (ORDER BY v) FROM hs
SELECT rank(99) WITHIN GROUP (ORDER BY v) FROM hs
SELECT rank(20) WITHIN GROUP (ORDER BY v DESC) FROM hs
SELECT rank(20) WITHIN GROUP (ORDER BY v NULLS FIRST) FROM hs
SELECT rank(20) WITHIN GROUP (ORDER BY v DESC NULLS LAST) FROM hs
SELECT rank(NULL) WITHIN GROUP (ORDER BY v) FROM hs
SELECT dense_rank(25) WITHIN GROUP (ORDER BY v) FROM hs
SELECT cume_dist(25) WITHIN GROUP (ORDER BY v) FROM hs
SELECT percent_rank(30) WITHIN GROUP (ORDER BY v) FROM hs
SELECT g, rank(20) WITHIN GROUP (ORDER BY v) FROM hs GROUP BY g ORDER BY g
SELECT rank(20) WITHIN GROUP (ORDER BY v) FROM hs WHERE false
SELECT dense_rank(20) WITHIN GROUP (ORDER BY v) FROM hs WHERE false
SELECT percent_rank(20) WITHIN GROUP (ORDER BY v) FROM hs WHERE false
SELECT cume_dist(20) WITHIN GROUP (ORDER BY v) FROM hs WHERE false
SELECT rank('b') WITHIN GROUP (ORDER BY g) FROM hs
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY v) FROM hs
SELECT percentile_disc(0.5) WITHIN GROUP (ORDER BY v) FROM hs
SELECT mode() WITHIN GROUP (ORDER BY v) FROM hs
