# VACUUM / ANALYZE / CHECKPOINT / REINDEX / CLUSTER / LOCK, against PostgreSQL 14.
VACUUM
VACUUM mt
VACUUM (VERBOSE false, ANALYZE) mt
VACUUM FULL mt
VACUUM nosuch
VACUUM mt (id)
ANALYZE
ANALYZE mt
ANALYZE mt (v)
ANALYZE nosuch
ANALYZE mt (nosuchcol)
CHECKPOINT
REINDEX TABLE mt
REINDEX INDEX mt_v
REINDEX TABLE nosuch
REINDEX INDEX nosuch
REINDEX (VERBOSE) TABLE mt
CLUSTER mt USING mt_v
SELECT id FROM mt
SELECT indexrelid::regclass::text, indisclustered FROM pg_index WHERE indrelid = 'mt'::regclass ORDER BY 1
CLUSTER mt
CLUSTER mt USING nosuch
CLUSTER nosuch
CLUSTER
CLUSTER mt USING mt_pkey
SELECT id FROM mt
INSERT INTO mt VALUES (0, 'z')
SELECT id FROM mt
CLUSTER mt USING mt_v
SELECT id FROM mt
ALTER TABLE mt SET WITHOUT CLUSTER
CLUSTER mt
ALTER TABLE mt CLUSTER ON mt_pkey
SELECT indexrelid::regclass::text, indisclustered FROM pg_index WHERE indrelid = 'mt'::regclass ORDER BY 1
ALTER TABLE mt CLUSTER ON nosuch
BEGIN
VACUUM mt
ROLLBACK
BEGIN
ANALYZE mt
CLUSTER mt USING mt_v
ROLLBACK
BEGIN
REINDEX TABLE mt
ROLLBACK
BEGIN
REINDEX DATABASE postgres
ROLLBACK
BEGIN
CHECKPOINT
ROLLBACK
LOCK TABLE mt
BEGIN
LOCK TABLE mt IN ACCESS EXCLUSIVE MODE
LOCK mt, mt IN ROW SHARE MODE NOWAIT
LOCK TABLE nosuch
ROLLBACK
BEGIN
LOCK TABLE mt IN SHARE MODE
SELECT count(*) FROM mt
COMMIT
