DROP TABLE IF EXISTS ins_a
DROP TABLE IF EXISTS ins_b
DROP MATERIALIZED VIEW IF EXISTS mv_s
DROP MATERIALIZED VIEW IF EXISTS mv_e
DROP TABLE IF EXISTS mv_t
CREATE TABLE mv_t (id int PRIMARY KEY, g text, n int)
INSERT INTO mv_t VALUES (1, 'a', 10), (2, 'a', 20), (3, 'b', 5)
