DROP TABLE IF EXISTS mt
DROP TABLE IF EXISTS ms
DROP TABLE IF EXISTS mlog
DROP FUNCTION IF EXISTS mlog_f() CASCADE
CREATE TABLE mt (id int PRIMARY KEY, v int)
CREATE TABLE ms (id int, v int)
CREATE TABLE mlog (n serial, what text)
CREATE FUNCTION mlog_f() RETURNS trigger LANGUAGE plpgsql AS $$ begin insert into mlog(what) values (TG_WHEN || ' ' || TG_OP || ' ' || TG_LEVEL); return null; end $$
CREATE TRIGGER t_bs BEFORE INSERT OR UPDATE OR DELETE ON mt FOR EACH STATEMENT EXECUTE FUNCTION mlog_f()
CREATE TRIGGER t_as AFTER INSERT OR UPDATE OR DELETE ON mt FOR EACH STATEMENT EXECUTE FUNCTION mlog_f()
INSERT INTO mt VALUES (1, 1), (2, 2), (3, 3)
INSERT INTO ms VALUES (1, 10), (2, 20), (4, 40), (5, 50)
