# ON CONFLICT arbiters inferred from a unique INDEX: a full one, and a
# partial one whose predicate the ON CONFLICT WHERE implies.
INSERT INTO pc VALUES (3, 10, true)
INSERT INTO pc VALUES (4, 10, true) ON CONFLICT (k) DO NOTHING
INSERT INTO pc VALUES (5, 11, true) ON CONFLICT (k) WHERE active DO NOTHING RETURNING *
INSERT INTO pc VALUES (6, 10, true) ON CONFLICT (k) WHERE active DO UPDATE SET active = excluded.active RETURNING *
INSERT INTO pc VALUES (7, 10, true) ON CONFLICT (k) WHERE active DO NOTHING RETURNING *
INSERT INTO pc VALUES (8, 20, false) ON CONFLICT (k) WHERE active DO NOTHING RETURNING *
INSERT INTO pc VALUES (9, 10, true) ON CONFLICT (k) WHERE k > 0 DO NOTHING
INSERT INTO pc VALUES (10, 10, true) ON CONFLICT (k) WHERE active AND k > 0 DO NOTHING RETURNING *
SELECT * FROM pc ORDER BY id
INSERT INTO pu VALUES (2, 10, 5) ON CONFLICT (k) DO UPDATE SET j = pu.j + 100 RETURNING *
INSERT INTO pu VALUES (3, 10, 5) ON CONFLICT (k) WHERE j > 0 DO NOTHING RETURNING *
INSERT INTO pu VALUES (4, 10, 101) ON CONFLICT (k, j) DO NOTHING RETURNING *
INSERT INTO pu VALUES (5, 11, 101) ON CONFLICT (j, k) DO UPDATE SET k = 99 RETURNING *
INSERT INTO pu VALUES (6, 10, 7) ON CONFLICT (j) DO NOTHING
INSERT INTO pu VALUES (7, 10, 7) ON CONFLICT ON CONSTRAINT pu_k DO NOTHING
SELECT * FROM pu ORDER BY id
INSERT INTO pk1 VALUES (3, 10, 'c') ON CONFLICT (k) DO UPDATE SET id = excluded.id RETURNING *
INSERT INTO pk1 VALUES (4, 20, 'd') ON CONFLICT (k) DO UPDATE SET id = 3 RETURNING *
INSERT INTO pk1 VALUES (5, 20, 'd') ON CONFLICT (k) DO UPDATE SET id = 5 RETURNING *
INSERT INTO pk1 VALUES (1, 30, 'e') ON CONFLICT (id) DO UPDATE SET id = pk1.id + 50 RETURNING *
INSERT INTO pk1 VALUES (3, 40, 'f') ON CONFLICT (id) DO UPDATE SET id = pk1.id + 50, v = excluded.v RETURNING *
SELECT * FROM pk1 ORDER BY id
SELECT * FROM fkc
