DROP TABLE IF EXISTS pt CASCADE
DROP TABLE IF EXISTS pl CASCADE
DROP TABLE IF EXISTS pt_2024
DROP TABLE IF EXISTS pt_2025
CREATE TABLE pt (id int, d date, v text) PARTITION BY RANGE (d)
CREATE TABLE pt_2023 PARTITION OF pt FOR VALUES FROM ('2023-01-01') TO ('2024-01-01')
CREATE TABLE pt_2024 PARTITION OF pt FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')
CREATE TABLE pl (id int, region text) PARTITION BY LIST (region)
CREATE TABLE pl_eu PARTITION OF pl FOR VALUES IN ('eu', 'uk')
CREATE TABLE pl_other PARTITION OF pl DEFAULT
