DROP TABLE IF EXISTS pe_l CASCADE
DROP TABLE IF EXISTS pe_r CASCADE
DROP TABLE IF EXISTS pe_o CASCADE
CREATE TABLE pe_l (id int, name text) PARTITION BY LIST (lower(name))
CREATE TABLE pe_l_ab PARTITION OF pe_l FOR VALUES IN ('a', 'b')
CREATE TABLE pe_l_c PARTITION OF pe_l FOR VALUES IN ('c')
CREATE TABLE pe_r (id int, d date) PARTITION BY RANGE ((id % 10))
CREATE TABLE pe_r_lo PARTITION OF pe_r FOR VALUES FROM (0) TO (5)
CREATE TABLE pe_r_hi PARTITION OF pe_r FOR VALUES FROM (5) TO (10)
CREATE TABLE pe_o (a int, b int) PARTITION BY RANGE (b, a)
CREATE TABLE pe_o1 PARTITION OF pe_o FOR VALUES FROM (0, 0) TO (10, 0)
CREATE TABLE pe_o2 PARTITION OF pe_o FOR VALUES FROM (10, 0) TO (20, 0)
