DROP TABLE IF EXISTS xpe_l CASCADE
DROP TABLE IF EXISTS xpe_r CASCADE
DROP TABLE IF EXISTS xpe_o CASCADE
CREATE TABLE xpe_l (id int, name text) PARTITION BY LIST (lower(name))
CREATE TABLE xpe_l_ab PARTITION OF xpe_l FOR VALUES IN ('a', 'b')
CREATE TABLE xpe_l_c PARTITION OF xpe_l FOR VALUES IN ('c')
CREATE TABLE xpe_r (id int, d date) PARTITION BY RANGE ((id % 10))
CREATE TABLE xpe_r_lo PARTITION OF xpe_r FOR VALUES FROM (0) TO (5)
CREATE TABLE xpe_r_hi PARTITION OF xpe_r FOR VALUES FROM (5) TO (10)
CREATE TABLE xpe_o (a int, b int) PARTITION BY RANGE (b, a)
CREATE TABLE xpe_o1 PARTITION OF xpe_o FOR VALUES FROM (0, 0) TO (10, 0)
CREATE TABLE xpe_o2 PARTITION OF xpe_o FOR VALUES FROM (10, 0) TO (20, 0)
