DROP TABLE IF EXISTS pcx CASCADE
CREATE TABLE pcx (id int, v int, s text) PARTITION BY RANGE (id)
CREATE TABLE pcx1 PARTITION OF pcx (v NOT NULL, s DEFAULT 'dflt', CONSTRAINT pcx1_v CHECK (v > 0)) FOR VALUES FROM (0) TO (10)
CREATE TABLE pcx2 PARTITION OF pcx (PRIMARY KEY (id)) FOR VALUES FROM (10) TO (20)
CREATE TABLE pcx3 PARTITION OF pcx (v CHECK (v < 5), s UNIQUE) FOR VALUES FROM (20) TO (30)
