DROP TABLE IF EXISTS m CASCADE
DROP TABLE IF EXISTS s CASCADE
DROP TABLE IF EXISTS np
DROP TABLE IF EXISTS lone
CREATE TABLE m (a int, b int, v text, PRIMARY KEY (a, b)) PARTITION BY RANGE (a, b)
CREATE TABLE m_lo PARTITION OF m FOR VALUES FROM (MINVALUE, MINVALUE) TO (10, 5)
CREATE TABLE m_mid PARTITION OF m FOR VALUES FROM (10, 5) TO (20, MAXVALUE)
CREATE TABLE s (id int, region text, yr int) PARTITION BY LIST (region)
CREATE TABLE s_eu PARTITION OF s FOR VALUES IN ('eu') PARTITION BY RANGE (yr)
CREATE TABLE s_eu_old PARTITION OF s_eu FOR VALUES FROM (2000) TO (2020)
CREATE TABLE s_eu_new PARTITION OF s_eu FOR VALUES FROM (2020) TO (2100)
CREATE TABLE s_null PARTITION OF s FOR VALUES IN (NULL, 'xx')
CREATE TABLE np (x int)
