DROP TABLE IF EXISTS unn
DROP TABLE IF EXISTS unx
DROP TABLE IF EXISTS und
DROP TABLE IF EXISTS uio
CREATE TABLE unn (a int UNIQUE NULLS NOT DISTINCT, b int, c int, UNIQUE NULLS NOT DISTINCT (b, c))
CREATE TABLE unx (a int)
CREATE TABLE und (a int UNIQUE NULLS DISTINCT)
CREATE TABLE uio (a int, b int)
