DROP PROCEDURE IF EXISTS pr_1(int, int)
DROP PROCEDURE IF EXISTS pr_2(int)
DROP PROCEDURE IF EXISTS pr_3(int)
DROP PROCEDURE IF EXISTS pr_4()
DROP FUNCTION IF EXISTS pr_f()
DROP FUNCTION IF EXISTS pr_o(int, text)
DROP FUNCTION IF EXISTS pr_p(int)
DROP TABLE IF EXISTS pr_t
