call prx14_p();
select * from prx14_t order by 1;
call prx14_e();
select * from prx14_t order by 1;
select prx14_f();
do $$ begin insert into prx14_t values (30); commit; insert into prx14_t values (31); rollback; end $$;
select * from prx14_t order by 1;
call prx14_q();
select * from prx14_t order by 1;
call prx14_c();
select * from prx14_t order by 1;
call prx14_x();
select * from prx14_t order by 1;
call prx14_s();
call prx14_call();
select * from prx14_t order by 1;
call prx14_bad();
call prx14_loop();
select * from prx14_t order by 1;
select prx14_g();
select * from prx14_t order by 1;
insert into prx14_u values (1);
select * from prx14_t order by 1;
select count(*) from prx14_u;
do $$ declare x int := 1; begin insert into prx14_t values (x * 1000); raise exception 'boom'; end $$;
select count(*) from prx14_t where n >= 1000;
do $$ begin begin insert into prx14_t values (7); raise exception 'inner'; exception when others then null; end; insert into prx14_t values (8); end $$;
select * from prx14_t where n in (7, 8) order by 1;
