call ptc_p();
select * from ptc_t order by 1;
call ptc_e();
select * from ptc_t order by 1;
select ptc_f();
do $$ begin insert into ptc_t values (30); commit; insert into ptc_t values (31); rollback; end $$;
select * from ptc_t order by 1;
call ptc_q();
select * from ptc_t order by 1;
call ptc_c();
select * from ptc_t order by 1;
call ptc_x();
select * from ptc_t order by 1;
call ptc_s();
call ptc_call();
select * from ptc_t order by 1;
call ptc_bad();
call ptc_loop();
select * from ptc_t order by 1;
select ptc_g();
select * from ptc_t order by 1;
insert into ptc_u values (1);
select * from ptc_t order by 1;
select count(*) from ptc_u;
do $$ declare x int := 1; begin insert into ptc_t values (x * 1000); raise exception 'boom'; end $$;
select count(*) from ptc_t where n >= 1000;
do $$ begin begin insert into ptc_t values (7); raise exception 'inner'; exception when others then null; end; insert into ptc_t values (8); end $$;
select * from ptc_t where n in (7, 8) order by 1;
