DROP TABLE IF EXISTS ptc_t;
DROP TABLE IF EXISTS ptc_u;
DROP PROCEDURE IF EXISTS ptc_p, ptc_e, ptc_q, ptc_c, ptc_x, ptc_s, ptc_io, ptc_o, ptc_call, ptc_bad, ptc_loop;
DROP FUNCTION IF EXISTS ptc_f, ptc_g, ptc_trg;
CREATE TABLE ptc_t (n int);
CREATE TABLE ptc_u (m int);
CREATE PROCEDURE ptc_p() LANGUAGE plpgsql AS $$ begin insert into ptc_t values (1); commit; insert into ptc_t values (2); rollback; insert into ptc_t values (3); end $$;
CREATE PROCEDURE ptc_e() LANGUAGE plpgsql AS $$ begin insert into ptc_t values (10); commit; insert into ptc_t values (11); raise exception 'boom'; end $$;
CREATE FUNCTION ptc_f() RETURNS int LANGUAGE plpgsql AS $$ begin commit; return 1; end $$;
CREATE PROCEDURE ptc_q() LANGUAGE plpgsql AS $$ begin call ptc_p(); end $$;
CREATE PROCEDURE ptc_c() LANGUAGE plpgsql AS $$ begin insert into ptc_t values (40); commit and chain; insert into ptc_t values (41); rollback and chain; end $$;
CREATE PROCEDURE ptc_x() LANGUAGE plpgsql AS $$ begin insert into ptc_t values (50); commit; exception when others then raise notice 'caught %', sqlerrm; end $$;
CREATE PROCEDURE ptc_s() LANGUAGE sql AS $$ insert into ptc_t values (60); commit $$;
CREATE PROCEDURE ptc_io(inout a int, b int) LANGUAGE plpgsql AS $$ begin a := a + b; end $$;
CREATE PROCEDURE ptc_o(x int, out y text) LANGUAGE plpgsql AS $$ begin y := 'v' || x; end $$;
CREATE PROCEDURE ptc_call() LANGUAGE plpgsql AS $$ declare a int := 1; t text; begin call ptc_io(a, 10); call ptc_o(5, t); insert into ptc_t values (a + length(t)); end $$;
CREATE PROCEDURE ptc_bad() LANGUAGE plpgsql AS $$ begin call ptc_io(1, 2); end $$;
CREATE PROCEDURE ptc_loop() LANGUAGE plpgsql AS $$ declare r record; begin for r in select g from generate_series(1,3) g loop insert into ptc_t values (r.g * 100); if r.g = 2 then commit; end if; end loop; rollback; end $$;
CREATE FUNCTION ptc_g() RETURNS int LANGUAGE plpgsql AS $$ begin begin insert into ptc_t values (-1); raise exception 'x'; exception when others then null; end; insert into ptc_t values (-2); return 1; end $$;
CREATE FUNCTION ptc_trg() RETURNS trigger LANGUAGE plpgsql AS $$ begin begin insert into ptc_t values (-10); perform 1/0; exception when division_by_zero then null; end; return new; end $$;
CREATE TRIGGER ptc_tr BEFORE INSERT ON ptc_u FOR EACH ROW EXECUTE FUNCTION ptc_trg();
