DROP TABLE IF EXISTS prx14_t;
DROP TABLE IF EXISTS prx14_u;
DROP PROCEDURE IF EXISTS prx14_p, prx14_e, prx14_q, prx14_c, prx14_x, prx14_s, prx14_io, prx14_o, prx14_call, prx14_bad, prx14_loop;
DROP FUNCTION IF EXISTS prx14_f, prx14_g, prx14_trg;
CREATE TABLE prx14_t (n int);
CREATE TABLE prx14_u (m int);
CREATE PROCEDURE prx14_p() LANGUAGE plpgsql AS $$ begin insert into prx14_t values (1); commit; insert into prx14_t values (2); rollback; insert into prx14_t values (3); end $$;
CREATE PROCEDURE prx14_e() LANGUAGE plpgsql AS $$ begin insert into prx14_t values (10); commit; insert into prx14_t values (11); raise exception 'boom'; end $$;
CREATE FUNCTION prx14_f() RETURNS int LANGUAGE plpgsql AS $$ begin commit; return 1; end $$;
CREATE PROCEDURE prx14_q() LANGUAGE plpgsql AS $$ begin call prx14_p(); end $$;
CREATE PROCEDURE prx14_c() LANGUAGE plpgsql AS $$ begin insert into prx14_t values (40); commit and chain; insert into prx14_t values (41); rollback and chain; end $$;
CREATE PROCEDURE prx14_x() LANGUAGE plpgsql AS $$ begin insert into prx14_t values (50); commit; exception when others then raise notice 'caught %', sqlerrm; end $$;
CREATE PROCEDURE prx14_s() LANGUAGE sql AS $$ insert into prx14_t values (60); commit $$;
CREATE PROCEDURE prx14_io(inout a int, b int) LANGUAGE plpgsql AS $$ begin a := a + b; end $$;
CREATE PROCEDURE prx14_o(x int, out y text) LANGUAGE plpgsql AS $$ begin y := 'v' || x; end $$;
CREATE PROCEDURE prx14_call() LANGUAGE plpgsql AS $$ declare a int := 1; t text; begin call prx14_io(a, 10); call prx14_o(5, t); insert into prx14_t values (a + length(t)); end $$;
CREATE PROCEDURE prx14_bad() LANGUAGE plpgsql AS $$ begin call prx14_io(1, 2); end $$;
CREATE PROCEDURE prx14_loop() LANGUAGE plpgsql AS $$ declare r record; begin for r in select g from generate_series(1,3) g loop insert into prx14_t values (r.g * 100); if r.g = 2 then commit; end if; end loop; rollback; end $$;
CREATE FUNCTION prx14_g() RETURNS int LANGUAGE plpgsql AS $$ begin begin insert into prx14_t values (-1); raise exception 'x'; exception when others then null; end; insert into prx14_t values (-2); return 1; end $$;
CREATE FUNCTION prx14_trg() RETURNS trigger LANGUAGE plpgsql AS $$ begin begin insert into prx14_t values (-10); perform 1/0; exception when division_by_zero then null; end; return new; end $$;
CREATE TRIGGER prx14_tr BEFORE INSERT ON prx14_u FOR EACH ROW EXECUTE FUNCTION prx14_trg();
