DROP TABLE IF EXISTS dpr_c CASCADE
DROP TABLE IF EXISTS dpr_p CASCADE
DROP TABLE IF EXISTS dpr_x CASCADE
DROP TABLE IF EXISTS dpr_part CASCADE
CREATE TABLE dpr_x (id int PRIMARY KEY)
CREATE TABLE dpr_p (id int PRIMARY KEY)
CREATE TABLE dpr_c (id int PRIMARY KEY, pid int REFERENCES dpr_p(id))
CREATE TABLE dpr_part (id int, k text) PARTITION BY LIST (k)
CREATE TABLE dpr_part_a PARTITION OF dpr_part FOR VALUES IN ('a')
