DROP VIEW IF EXISTS pq_v
DROP TABLE IF EXISTS pq_t CASCADE
DROP SEQUENCE IF EXISTS pq_s
DROP FUNCTION IF EXISTS pq_f(int)
DROP TYPE IF EXISTS pq_e
CREATE TABLE pq_t (id int PRIMARY KEY, name text)
CREATE VIEW pq_v AS SELECT id, name FROM pq_t
CREATE SEQUENCE pq_s START 5
CREATE FUNCTION pq_f(x int) RETURNS int LANGUAGE sql AS 'select x + 1'
CREATE TYPE pq_e AS ENUM ('a', 'b')
