DROP VIEW IF EXISTS dpq_v
DROP TABLE IF EXISTS dpq_t CASCADE
DROP SEQUENCE IF EXISTS dpq_s
DROP FUNCTION IF EXISTS dpq_f(int)
DROP TYPE IF EXISTS dpq_e
CREATE TABLE dpq_t (id int PRIMARY KEY, name text)
CREATE VIEW dpq_v AS SELECT id, name FROM dpq_t
CREATE SEQUENCE dpq_s START 5
CREATE FUNCTION dpq_f(x int) RETURNS int LANGUAGE sql AS 'select x + 1'
CREATE TYPE dpq_e AS ENUM ('a', 'b')
