DROP TABLE IF EXISTS pr_c CASCADE
DROP TABLE IF EXISTS pr_p CASCADE
DROP TABLE IF EXISTS pr_x CASCADE
DROP TABLE IF EXISTS pr_part CASCADE
CREATE TABLE pr_x (id int PRIMARY KEY)
CREATE TABLE pr_p (id int PRIMARY KEY)
CREATE TABLE pr_c (id int PRIMARY KEY, pid int REFERENCES pr_p(id))
CREATE TABLE pr_part (id int, k text) PARTITION BY LIST (k)
CREATE TABLE pr_part_a PARTITION OF pr_part FOR VALUES IN ('a')
