DROP SCHEMA IF EXISTS ro_s CASCADE
DROP FUNCTION IF EXISTS ro_f(int, text)
DROP TABLE IF EXISTS ro_t
CREATE SCHEMA ro_s
CREATE FUNCTION ro_f(a int, b text) RETURNS int LANGUAGE sql AS 'SELECT 1'
CREATE TABLE ro_t (id int)
