DROP ROLE IF EXISTS rm_c
DROP ROLE IF EXISTS rm_d
DROP ROLE IF EXISTS rm_e
DROP ROLE IF EXISTS rm_b
DROP ROLE IF EXISTS rm_a
CREATE ROLE rm_a
CREATE ROLE rm_b IN ROLE rm_a
CREATE ROLE rm_c ROLE rm_b
CREATE ROLE rm_d ADMIN rm_b
CREATE ROLE rm_e
