SET search_path TO "$user", public
DROP SCHEMA IF EXISTS sc34_a CASCADE
DROP SCHEMA IF EXISTS sc34_b CASCADE
DROP SCHEMA IF EXISTS sc34_c CASCADE
DROP TABLE IF EXISTS sc34_users CASCADE
DROP TABLE IF EXISTS sc34_pub
CREATE SCHEMA sc34_a
CREATE SCHEMA sc34_b
CREATE TABLE sc34_users (user_id serial PRIMARY KEY, x int)
INSERT INTO sc34_users (x) VALUES (1), (2)
