DROP TABLE IF EXISTS sq11
DROP SEQUENCE IF EXISTS s11
CREATE SEQUENCE s11 START 10 INCREMENT 2 MINVALUE 1 MAXVALUE 100
CREATE TABLE sq11 (id serial PRIMARY KEY, big bigserial, n int)
INSERT INTO sq11 (n) VALUES (1), (2)
