SELECT nextval('s11'), nextval('s11'), currval('s11')
SELECT setval('s11', 50), nextval('s11')
SELECT setval('s11', 50, false), nextval('s11')
SELECT last_value FROM s11
SELECT * FROM sq11 ORDER BY id
INSERT INTO sq11 (n) VALUES (3) RETURNING id, big
SELECT currval('sq11_id_seq')
SELECT pg_get_serial_sequence('sq11', 'id')
ALTER SEQUENCE s11 RESTART WITH 5
SELECT nextval('s11')
ALTER SEQUENCE s11 INCREMENT BY 10
SELECT nextval('s11')
SELECT nextval('nope11')
SELECT sequence_name FROM information_schema.sequences WHERE sequence_name='s11'
DROP SEQUENCE s11
SELECT nextval('s11')
# --- identity columns
CREATE TABLE idt11 (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, v int)
INSERT INTO idt11 (v) VALUES (1), (2)
SELECT * FROM idt11 ORDER BY id
INSERT INTO idt11 (id, v) VALUES (99, 3)
INSERT INTO idt11 (id, v) OVERRIDING SYSTEM VALUE VALUES (99, 3)
SELECT count(*) FROM idt11
CREATE TABLE idt12 (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v int)
INSERT INTO idt12 (id, v) VALUES (7, 1)
INSERT INTO idt12 (v) VALUES (2)
SELECT id FROM idt12 ORDER BY id
