# --- defaults, and what a fresh sequence reads as
CREATE SEQUENCE w1
SELECT last_value, is_called FROM w1
SELECT nextval('w1'), nextval('w1')
SELECT last_value, is_called FROM w1
# --- a DESCENDING sequence starts at its MAXIMUM, not at 1
CREATE SEQUENCE w2 INCREMENT -1
SELECT nextval('w2'), nextval('w2')
DROP SEQUENCE w2
CREATE SEQUENCE w2 INCREMENT -3 MINVALUE -10 MAXVALUE -1
SELECT nextval('w2'), nextval('w2'), nextval('w2'), nextval('w2')
SELECT nextval('w2')
# --- bounds and exhaustion
CREATE SEQUENCE w3 START 1 MAXVALUE 3
SELECT nextval('w3'), nextval('w3'), nextval('w3')
SELECT nextval('w3')
CREATE SEQUENCE w4 MINVALUE 5 MAXVALUE 2
CREATE SEQUENCE w4 START 100 MINVALUE 1 MAXVALUE 10
CREATE SEQUENCE w4 INCREMENT 0
# --- currval before any nextval in this session
CREATE SEQUENCE w4 START 7
SELECT currval('w4')
SELECT nextval('w4')
SELECT currval('w4')
# --- setval, both forms, and out of bounds
SELECT setval('w4', 20)
SELECT currval('w4')
SELECT nextval('w4')
SELECT setval('w4', 30, false)
SELECT nextval('w4')
SELECT setval('w4', 0)
# --- a missing sequence
SELECT nextval('nope_w')
SELECT currval('nope_w')
SELECT setval('nope_w', 1)
DROP SEQUENCE nope_w
DROP SEQUENCE IF EXISTS nope_w
CREATE SEQUENCE w4
CREATE SEQUENCE IF NOT EXISTS w4
# --- ALTER SEQUENCE applies only what it names
ALTER SEQUENCE w4 INCREMENT BY 100
SELECT nextval('w4')
ALTER SEQUENCE w4 RESTART
SELECT nextval('w4')
ALTER SEQUENCE w4 RESTART WITH 500
SELECT nextval('w4'), nextval('w4')
ALTER SEQUENCE w4 MAXVALUE 601
SELECT nextval('w4')
ALTER SEQUENCE nope_w RESTART
ALTER SEQUENCE IF EXISTS nope_w RESTART
# --- NULL arguments are NULL results, not errors
SELECT nextval(NULL)
SELECT setval(NULL, 1)
# --- serial and pg_get_serial_sequence
CREATE TABLE srw1 (id serial PRIMARY KEY, big bigserial, n int)
INSERT INTO srw1 (n) VALUES (1), (2), (3)
SELECT id, big FROM srw1 ORDER BY id
SELECT currval('srw1_id_seq'), currval('srw1_big_seq')
SELECT pg_get_serial_sequence('srw1', 'id')
SELECT pg_get_serial_sequence('srw1', 'n')
# a relation or a column that is not there is an error, not NULL
SELECT pg_get_serial_sequence('nosuch_srw', 'id')
SELECT pg_get_serial_sequence('public.NoSuch_srw', 'id')
SELECT pg_get_serial_sequence('srw1', 'nope')
# --- identity: ALWAYS refuses a hand-written value, BY DEFAULT takes it
CREATE TABLE idw1 (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, v int)
INSERT INTO idw1 (v) VALUES (1), (2)
SELECT id, v FROM idw1 ORDER BY id
INSERT INTO idw1 (id, v) VALUES (50, 3)
INSERT INTO idw1 (id, v) OVERRIDING SYSTEM VALUE VALUES (50, 3)
SELECT id FROM idw1 ORDER BY id
INSERT INTO idw1 (id, v) OVERRIDING USER VALUE VALUES (60, 4)
SELECT count(*) FROM idw1
CREATE TABLE idw2 (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v int)
INSERT INTO idw2 (id, v) VALUES (7, 1)
INSERT INTO idw2 (v) VALUES (2)
SELECT id FROM idw2 ORDER BY id
INSERT INTO idw2 (id, v) VALUES (NULL, 3)
# --- CYCLE wraps to the far bound instead of failing
DROP SEQUENCE IF EXISTS w5
CREATE SEQUENCE w5 START 1 MAXVALUE 3 CYCLE
SELECT nextval('w5'), nextval('w5'), nextval('w5'), nextval('w5'), nextval('w5')
DROP SEQUENCE IF EXISTS w6
CREATE SEQUENCE w6 INCREMENT -1 MINVALUE 1 MAXVALUE 3 CYCLE
SELECT nextval('w6'), nextval('w6'), nextval('w6'), nextval('w6')
