# --- pattern / regex corners not covered before
SELECT regexp_replace('a1b2c3', '[0-9]', 'X', 'g'), regexp_replace('aaa', 'a', 'X', 'gi')
SELECT regexp_replace('abc', '(b)', '[\1]'), regexp_replace('abc', 'b', '\&\&')
SELECT regexp_count('a1b2c3', '[0-9]'), regexp_instr('a1b2', '[0-9]'), regexp_like('abc','b')
SELECT regexp_substr('a1b22c', '[0-9]+'), regexp_substr('a1b22c', '[0-9]+', 1, 2)
SELECT regexp_split_to_array('a1b22c', '[0-9]+'), regexp_split_to_table('a,b', ',')
SELECT 'abc' ~ '^a', 'abc' ~ 'c$', 'aXbc' ~ 'a.b'
SELECT substring('abc' from '(b)'), substring('abc' from 'x')
SELECT regexp_matches('a1b2', '[0-9]', 'g')
# --- text edges
SELECT lpad('abc', 3), rpad('abc', 3), lpad('', 3, 'x')
SELECT split_part('a,b,c', ',', -1), split_part('abc', '', 1)
SELECT left('abc', -10), right('abc', -10)
SELECT substr('abc', 2), substr('abc', -5, 3)
SELECT overlay('abc' placing 'XY' from 1 for 0)
SELECT translate('abc', 'abc', 'xy')
SELECT btrim('xyxabcyx', 'xy'), ltrim('xyabc', 'xy'), rtrim('abcxy', 'xy')
SELECT concat_ws(',', 1, 2, NULL, 3), concat(1, 2.5, true)
SELECT to_hex(4294967295), to_hex(-2)
SELECT chr(65), chr(955), ascii('λ')
SELECT length(E'a\\nb'), octet_length('λ'), char_length('λ')
SELECT upper('ß'), lower('İ'), initcap('ßx')
SELECT reverse('λx'), md5(''), starts_with('', '')
SELECT repeat('ab', 3) || repeat('c', 0)
SELECT format('%s %s', 'a'), format('%3$s', 'a','b','c')
SELECT quote_literal(1), quote_literal(NULL), quote_nullable('a')
SELECT t, c, t || c FROM s9t ORDER BY id
SELECT trim(both from '  x  '), trim(leading from '  x'), trim('  x  ')
SELECT position('' in ''), strpos('', '')
SELECT ('abc' COLLATE "C") < 'abd'
SELECT to_ascii('abc')
SELECT convert_from('abc'::bytea, 'UTF8')
SELECT encode('abc'::bytea, 'base64'), decode('YWJj', 'base64')
SELECT encode('abc'::bytea, 'hex'), encode('abc'::bytea, 'escape')
SELECT unistr('d\\0061t\\+000061')
SELECT normalize('a'), normalize('a', NFC)
SELECT 'a' || NULL, concat('a', NULL)
