DROP TABLE IF EXISTS tl_a
DROP TABLE IF EXISTS tl_b
DROP TABLE IF EXISTS tl_c
DROP TABLE IF EXISTS tl_src
CREATE TABLE tl_src (id int PRIMARY KEY, name text NOT NULL DEFAULT 'x', n int CHECK (n > 0), u text UNIQUE, g int GENERATED ALWAYS AS (n * 2) STORED)
