CREATE TRIGGER tr_a AFTER INSERT ON tr_t REFERENCING NEW TABLE AS nt FOR EACH STATEMENT EXECUTE FUNCTION tr_ins()
CREATE TRIGGER tr_b AFTER UPDATE ON tr_t REFERENCING OLD TABLE AS ot NEW TABLE AS nt FOR EACH STATEMENT EXECUTE FUNCTION tr_upd()
CREATE TRIGGER tr_c AFTER DELETE ON tr_t REFERENCING OLD TABLE AS ot FOR EACH STATEMENT EXECUTE FUNCTION tr_del()
INSERT INTO tr_t VALUES (1, 10), (2, 20), (3, 30)
UPDATE tr_t SET n = n + 1 WHERE id < 3
DELETE FROM tr_t WHERE id > 1
INSERT INTO tr_t SELECT 9, 9 WHERE false
SELECT msg FROM tr_log ORDER BY msg
SELECT count(*) FROM pg_class WHERE relname IN ('nt', 'ot') AND relpersistence = 't'
CREATE TRIGGER tr_bad BEFORE INSERT ON tr_t REFERENCING NEW TABLE AS x FOR EACH STATEMENT EXECUTE FUNCTION tr_ins()
CREATE TRIGGER tr_bad2 AFTER INSERT ON tr_t REFERENCING OLD TABLE AS x FOR EACH STATEMENT EXECUTE FUNCTION tr_ins()
CREATE TRIGGER tr_bad3 AFTER INSERT OR DELETE ON tr_t REFERENCING NEW TABLE AS x FOR EACH STATEMENT EXECUTE FUNCTION tr_ins()
CREATE TRIGGER tr_bad4 AFTER UPDATE ON tr_t REFERENCING NEW TABLE AS x OLD TABLE AS x FOR EACH STATEMENT EXECUTE FUNCTION tr_ins()
