BEGIN
INSERT INTO tx12 VALUES (3, 30)
SELECT count(*) FROM tx12
ROLLBACK
SELECT count(*) FROM tx12
BEGIN
INSERT INTO tx12 VALUES (4, 40)
COMMIT
SELECT count(*) FROM tx12
BEGIN
SAVEPOINT sp1
INSERT INTO tx12 VALUES (5, 50)
ROLLBACK TO SAVEPOINT sp1
SELECT count(*) FROM tx12
RELEASE SAVEPOINT sp1
COMMIT
SELECT count(*) FROM tx12
BEGIN
SELECT 1/0
SELECT 1
ROLLBACK
SELECT 1
COMMIT
ROLLBACK
SAVEPOINT nope
BEGIN
ROLLBACK TO SAVEPOINT nosuch
ROLLBACK
SHOW transaction_isolation
BEGIN ISOLATION LEVEL SERIALIZABLE
SHOW transaction_isolation
COMMIT
BEGIN READ ONLY
INSERT INTO tx12 VALUES (9, 90)
ROLLBACK
SELECT count(*) FROM tx12
BEGIN
CREATE TABLE tmp12 (a int)
ROLLBACK
SELECT count(*) FROM tmp12
BEGIN READ ONLY
UPDATE tx12 SET n = 0
ROLLBACK
BEGIN READ ONLY
CREATE TABLE ro12 (a int)
ROLLBACK
BEGIN READ ONLY
SELECT count(*) FROM tx12
COMMIT
SET default_transaction_read_only = on
DELETE FROM tx12
SET default_transaction_read_only = off
DELETE FROM tx12 WHERE id = 9
