DROP VIEW IF EXISTS pvv
DROP TABLE IF EXISTS pbase
DROP TABLE IF EXISTS pother
DROP ROLE IF EXISTS pu
CREATE ROLE pu LOGIN
CREATE TABLE pbase (id int, v text)
INSERT INTO pbase VALUES (1,'a'),(2,'b')
CREATE TABLE pother (id int)
INSERT INTO pother VALUES (1)
CREATE VIEW pvv AS SELECT id, v FROM pbase WHERE id > 0
GRANT SELECT ON pvv TO pu
