DROP VIEW IF EXISTS vd_cols
DROP VIEW IF EXISTS vd_loc2
DROP VIEW IF EXISTS vd_cas2
DROP VIEW IF EXISTS vd_plain
DROP VIEW IF EXISTS vd_chk
DROP VIEW IF EXISTS vd_vv
DROP VIEW IF EXISTS vd_agg
DROP VIEW IF EXISTS vd_v
DROP TABLE IF EXISTS vd_t
CREATE TABLE vd_t (id int PRIMARY KEY, g text, n int DEFAULT 7)
INSERT INTO vd_t VALUES (1, 'a', 10), (2, 'a', 20), (3, 'b', 30)
CREATE VIEW vd_v AS SELECT id, g AS grp, n, n * 2 AS dbl FROM vd_t WHERE n >= 20
CREATE VIEW vd_vv AS SELECT id, grp FROM vd_v WHERE grp = 'a'
CREATE VIEW vd_agg AS SELECT g, count(*) AS c FROM vd_t GROUP BY g
CREATE VIEW vd_chk AS SELECT id, n FROM vd_t WHERE n > 0 WITH CHECK OPTION
CREATE VIEW vd_plain AS SELECT id, n FROM vd_t WHERE n < 100
CREATE VIEW vd_cas2 AS SELECT id, n FROM vd_plain WHERE n > 5 WITH CASCADED CHECK OPTION
CREATE VIEW vd_loc2 AS SELECT id, n FROM vd_plain WHERE n > 5 WITH LOCAL CHECK OPTION
CREATE VIEW vd_cols (k, label) AS SELECT id, g FROM vd_t
