DROP VIEW IF EXISTS vd14_vals, vd14_vals2, vd14_vals3, vd14_win, vd14_w2, vd14_w3, vd14_lat, vd14_cols, vd14_set, vd14_set2, vd14_rec, vd14_ex, vd14_cte, vd14_ra, vd14_rec2;
DROP TABLE IF EXISTS vd14_t;
CREATE TABLE vd14_t (id int, g int, v numeric, t text);
INSERT INTO vd14_t VALUES (1, 10, 1.5, 'a'), (2, 20, 2.5, 'b'), (3, 10, 3.5, 'c');
CREATE VIEW vd14_vals AS select * from (values (1, 'a'), (2, 'b')) v(n, s);
CREATE VIEW vd14_vals2 AS select * from (values (1, 'a'), (2, 'b')) v;
CREATE VIEW vd14_vals3 AS values (1, 2.5), (2, 3);
CREATE VIEW vd14_win AS select id, sum(v) over (partition by g order by id rows between 1 preceding and current row) as s from vd14_t;
CREATE VIEW vd14_w2 AS select id, count(*) over (order by id groups between unbounded preceding and 1 following exclude ties) from vd14_t;
CREATE VIEW vd14_w3 AS select id, count(*) over (rows unbounded preceding) from vd14_t;
CREATE VIEW vd14_lat AS select r.id, x.n from vd14_t r, lateral (select r.g * 2 as n) x;
CREATE VIEW vd14_cols AS select a.i, a.j from (select id, g from vd14_t) a(i, j);
CREATE VIEW vd14_set AS select id from vd14_t union select g from vd14_t order by 1 limit 5;
CREATE VIEW vd14_set2 AS select id from vd14_t union all select g from vd14_t order by id desc offset 1;
CREATE VIEW vd14_rec AS with recursive r(n) as (select 1 union all select n + 1 from r where n < 5) select n from r;
CREATE VIEW vd14_rec2 AS with recursive r(n) as (select 1 union all select n + 1 from r where n < 3) select n * 10 as m from r;
CREATE VIEW vd14_ex AS select id from vd14_t where exists (select 1 from vd14_t where vd14_t.g = 10);
CREATE VIEW vd14_cte AS with c(x) as (select id from vd14_t) select x from c;
CREATE VIEW vd14_ra AS select r.a from vd14_t r(a, b);
