select pg_get_viewdef('vd14_vals');
select pg_get_viewdef('vd14_vals2');
select pg_get_viewdef('vd14_vals3');
select pg_get_viewdef('vd14_win');
select pg_get_viewdef('vd14_w2');
select pg_get_viewdef('vd14_w3');
select pg_get_viewdef('vd14_lat');
select pg_get_viewdef('vd14_cols');
select pg_get_viewdef('vd14_set');
select pg_get_viewdef('vd14_set2');
select pg_get_viewdef('vd14_rec');
select pg_get_viewdef('vd14_rec2');
select pg_get_viewdef('vd14_ex');
select pg_get_viewdef('vd14_cte');
select pg_get_viewdef('vd14_ra');
select * from vd14_vals2 order by 1;
select * from vd14_rec order by 1;
select * from vd14_rec2 order by 1;
select * from vd14_set order by 1;
select * from vd14_win order by 1;
select * from vd14_ra order by 1;
select r.a, r.b from vd14_t r(a, b) where r.b > 10 order by 1;
select count(*) from vd14_t as x(p, q) where q = 10;
