CREATE VIEW vv1 AS SELECT id, g, n FROM vt WHERE n IS NOT NULL
SELECT * FROM vv1 ORDER BY id
SELECT id FROM vv1 WHERE n > 15 ORDER BY id
SELECT g, sum(n) FROM vv1 GROUP BY g ORDER BY g
SELECT count(*) FROM vv1
SELECT v.id, vt2.label FROM vv1 v JOIN vt2 ON vt2.id = v.id ORDER BY v.id
SELECT id FROM vt WHERE id IN (SELECT id FROM vv1) ORDER BY id
SELECT * FROM (SELECT id FROM vv1) s ORDER BY id
SELECT id FROM vv1 UNION SELECT id FROM vt2 ORDER BY 1
WITH c AS (SELECT * FROM vv1) SELECT count(*) FROM c
CREATE VIEW vv2 (k, total) AS SELECT g, sum(n) FROM vt GROUP BY g
SELECT * FROM vv2 ORDER BY k
SELECT total FROM vv2 WHERE k = 'b'
CREATE VIEW vv3 AS SELECT k FROM vv2 WHERE total > 25
SELECT * FROM vv3
SELECT * FROM vv1 v1 JOIN vv2 v2 ON v2.k = v1.g ORDER BY v1.id
# --- errors at CREATE
CREATE VIEW vv1 AS SELECT 1
CREATE VIEW vbad AS SELECT nosuch FROM vt
CREATE VIEW vbad AS SELECT * FROM nosuch
CREATE VIEW vbad (a, b, c, d) AS SELECT id, g FROM vt
CREATE VIEW vt AS SELECT 1
CREATE TABLE vv1 (x int)
# --- OR REPLACE
CREATE OR REPLACE VIEW vv1 AS SELECT id, g, n, n * 2 AS dbl FROM vt WHERE n IS NOT NULL
SELECT dbl FROM vv1 ORDER BY id
CREATE OR REPLACE VIEW vv1 AS SELECT id, g FROM vt
CREATE OR REPLACE VIEW vv1 AS SELECT id, g AS gg, n, n * 2 AS dbl FROM vt
CREATE OR REPLACE VIEW vv1 AS SELECT id, g, n::text AS n, n * 2 AS dbl FROM vt
CREATE OR REPLACE VIEW vnew AS SELECT 1 AS one
SELECT * FROM vnew
# --- writes through a view, and drops
INSERT INTO vv1 (id, g, n) VALUES (9, 'z', 1)
DROP TABLE vt
DROP TABLE vv1
DROP VIEW vt
DROP VIEW vv2
DROP VIEW nosuch
DROP VIEW IF EXISTS nosuch
DROP VIEW vv3, vv2
SELECT count(*) FROM vv2
DROP VIEW vnew
BEGIN
CREATE VIEW vtx AS SELECT id FROM vt
SELECT count(*) FROM vtx
ROLLBACK
SELECT count(*) FROM vtx
