# RANGE frames whose bounds are BOTH on the same side of the current row --
# the shapes the first corpora never reached.
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN 1 FOLLOWING AND 20 FOLLOWING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN 20 PRECEDING AND 1 PRECEDING) FROM w9 ORDER BY id
SELECT id, count(*) OVER (ORDER BY v RANGE BETWEEN 5 FOLLOWING AND 10 FOLLOWING) FROM w9 ORDER BY id
SELECT id, count(*) OVER (ORDER BY v DESC RANGE BETWEEN 1 FOLLOWING AND 20 FOLLOWING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN 0 PRECEDING AND 0 FOLLOWING) FROM w9 ORDER BY id
# GROUPS with both bounds on one side
SELECT id, count(*) OVER (ORDER BY v GROUPS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) FROM w9 ORDER BY id
SELECT id, count(*) OVER (ORDER BY v GROUPS BETWEEN 2 PRECEDING AND 1 PRECEDING) FROM w9 ORDER BY id
# ROWS with both bounds on one side, for comparison
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) FROM w9 ORDER BY id
