# --- frames
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN 2 PRECEDING AND 1 PRECEDING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id ROWS 2 PRECEDING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN 5 PRECEDING AND 5 FOLLOWING) FROM w9 ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM w9 ORDER BY id
SELECT id, count(*) OVER (PARTITION BY g ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w9 ORDER BY id
SELECT id, last_value(v) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w9 ORDER BY id
SELECT id, first_value(v) OVER (PARTITION BY g ORDER BY id) FROM w9 ORDER BY id
SELECT id, nth_value(v, 2) OVER (PARTITION BY g ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w9 ORDER BY id
# --- window naming / EXCLUDE / filter
SELECT id, sum(v) OVER w FROM w9 WINDOW w AS (ORDER BY id) ORDER BY id
SELECT id, sum(v) OVER (w ORDER BY id) FROM w9 WINDOW w AS (PARTITION BY g) ORDER BY id
SELECT id, sum(v) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW) FROM w9 ORDER BY id
SELECT id, count(*) FILTER (WHERE v > 10) OVER (ORDER BY id) FROM w9 ORDER BY id
# --- ranking / distribution with nulls and ties
SELECT id, rank() OVER (ORDER BY v), dense_rank() OVER (ORDER BY v) FROM w9 ORDER BY id
SELECT id, rank() OVER (ORDER BY v NULLS FIRST) FROM w9 ORDER BY id
SELECT id, row_number() OVER (PARTITION BY g ORDER BY v DESC) FROM w9 ORDER BY id
SELECT id, ntile(3) OVER (ORDER BY id) FROM w9 ORDER BY id
SELECT id, percent_rank() OVER (ORDER BY v), cume_dist() OVER (ORDER BY v) FROM w9 ORDER BY id
SELECT id, lag(v, 1, -1) OVER (PARTITION BY g ORDER BY id), lead(v) OVER (PARTITION BY g ORDER BY id) FROM w9 ORDER BY id
SELECT id, avg(v) OVER (PARTITION BY g), max(v) OVER (), min(v) OVER (PARTITION BY g ORDER BY id) FROM w9 ORDER BY id
SELECT DISTINCT g, sum(v) OVER (PARTITION BY g) FROM w9 ORDER BY g
SELECT g, sum(sum(v)) OVER (ORDER BY g) FROM w9 GROUP BY g ORDER BY g
SELECT id, string_agg(g, ',') OVER (ORDER BY id) FROM w9 ORDER BY id
SELECT id, array_agg(v) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM w9 ORDER BY id
