"""Generate `crates/secantus-core/src/timelib/zones.rs` from timelib's zone maps.

The inputs are mongod 8.2.11's own copies of timelib 2022.13's
`timezonemap.h` (src/third_party/timelib/dist), kept here
beside this script. The abbreviation lookup returns the FIRST matching entry, so
order is part of the data: never sort or dedupe it.

    python tools/timelib/gen_zone_tables.py
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent / "crates" / "secantus-core" / "src" / "timelib" / "zones.rs"
# The military zones `a`..`z` carry NULL as their full name -- they must be kept.
ROW = re.compile(
    r'\{\s*"([^"]*)",\s*(\d+),\s*([-+]?\s*\d+(?:\s*\*\s*\d+)?),\s*(?:"([^"]*)"|NULL)\s*\}'
)


def rows(path: Path) -> list[tuple[str, int, int, str]]:
    out = []
    for m in ROW.finditer(path.read_text()):
        name, dst, off, full = m.groups()
        out.append((name, int(dst), eval(off.replace(" ", "")), full or ""))  # noqa: S307 -- integer arithmetic from a header we vendor
    return out


def render(name: str, data: list[tuple[str, int, int, str]]) -> str:
    lines = [f"pub(crate) static {name}: &[TzEntry] = &["]
    for abbr, dst, off, full in data:
        lines.append(
            f'    TzEntry {{ name: "{abbr}", dst: {dst}, gmtoffset: {off}, full: "{full}" }},'
        )
    lines.append("];")
    return "\n".join(lines)


def main() -> None:
    zones = rows(HERE / "timezonemap.h")
    # Every non-blank line of each header is a row; a skipped one would be a
    # silently missing zone.
    for path, got in ((HERE / "timezonemap.h", zones),):
        want = sum(1 for line in path.read_text().splitlines() if line.strip())
        assert len(got) == want, (path.name, len(got), want)
    OUT.write_text(
        "//! GENERATED by tools/timelib/gen_zone_tables.py from timelib 2022.13's\n"
        "//! timezonemap.h as vendored by mongod 8.2.11. Do not edit.\n"
        "//! Copyright (c) 2015-2021 Derick Rethans, (c) 2017-2019,2021 MongoDB, Inc.\n"
        "//! MIT License (src/timelib/LICENSE-timelib.rst in this crate).\n\n"
        "#![allow(clippy::all)]\n\n"
        "pub(crate) struct TzEntry {\n"
        "    pub name: &'static str,\n"
        "    pub dst: i64,\n"
        "    pub gmtoffset: i64,\n"
        "    #[allow(dead_code)]\n"
        "    pub full: &'static str,\n"
        "}\n\n" + render("TIMEZONE_MAP", zones) + "\n"
    )
    # Format as `cargo fmt` would, so a regeneration can never fail CI's
    # `cargo fmt --check` (a raw regeneration once did).
    subprocess.run(["rustfmt", "--edition", "2021", str(OUT)], check=True)
    print(f"{OUT}: {len(zones)} zones")


if __name__ == "__main__":
    main()
